# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/nagafusa/work/spadi/Fakernet/axi_iic_0_ex/imports/axi_iic_0_exdes.xdc

# IP: ip/axi_iic_0/axi_iic_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_iic_0 || ORIG_REF_NAME==axi_iic_0} -quiet] -quiet
