# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/GTH.xdc

# XDC: new/main_io.xdc

# XDC: new/samidare_io.xdc

# XDC: new/Pblock.xdc

# IP: ip/gig_ethernet_pcs_pma_0_gt/gig_ethernet_pcs_pma_0_gt.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==gig_ethernet_pcs_pma_0_gt || ORIG_REF_NAME==gig_ethernet_pcs_pma_0_gt} -quiet] -quiet

# Block Designs: bd/top_block/top_block.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block || ORIG_REF_NAME==top_block} -quiet] -quiet

# IP: bd/top_block/ip/top_block_util_vector_logic_0_2/top_block_util_vector_logic_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block_util_vector_logic_0_2 || ORIG_REF_NAME==top_block_util_vector_logic_0_2} -quiet] -quiet

# IP: bd/top_block/ip/top_block_xlconstant_0_2/top_block_xlconstant_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block_xlconstant_0_2 || ORIG_REF_NAME==top_block_xlconstant_0_2} -quiet] -quiet

# IP: bd/top_block/ip/top_block_LED_REG_READ_SEPARAT_0_0/top_block_LED_REG_READ_SEPARAT_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block_LED_REG_READ_SEPARAT_0_0 || ORIG_REF_NAME==top_block_LED_REG_READ_SEPARAT_0_0} -quiet] -quiet

# IP: bd/top_block/ip/top_block_LED_REG_READ_SEPARAT_1_0/top_block_LED_REG_READ_SEPARAT_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block_LED_REG_READ_SEPARAT_1_0 || ORIG_REF_NAME==top_block_LED_REG_READ_SEPARAT_1_0} -quiet] -quiet

# IP: bd/top_block/ip/top_block_u_led_inst_0_0/top_block_u_led_inst_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block_u_led_inst_0_0 || ORIG_REF_NAME==top_block_u_led_inst_0_0} -quiet] -quiet

# IP: bd/top_block/ip/top_block_vio_0_0/top_block_vio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block_vio_0_0 || ORIG_REF_NAME==top_block_vio_0_0} -quiet] -quiet

# IP: bd/top_block/ip/top_block_rst_clk_wiz_0_125M_0/top_block_rst_clk_wiz_0_125M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block_rst_clk_wiz_0_125M_0 || ORIG_REF_NAME==top_block_rst_clk_wiz_0_125M_0} -quiet] -quiet

# IP: bd/top_block/ip/top_block_xpm_cdc_gen_0_0/top_block_xpm_cdc_gen_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block_xpm_cdc_gen_0_0 || ORIG_REF_NAME==top_block_xpm_cdc_gen_0_0} -quiet] -quiet

# IP: bd/top_block/ip/top_block_rst_clk_wiz_1_320M_0/top_block_rst_clk_wiz_1_320M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block_rst_clk_wiz_1_320M_0 || ORIG_REF_NAME==top_block_rst_clk_wiz_1_320M_0} -quiet] -quiet

# IP: bd/top_block/ip/top_block_axi_bram_ctrl_0_0/top_block_axi_bram_ctrl_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block_axi_bram_ctrl_0_0 || ORIG_REF_NAME==top_block_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/top_block/ip/top_block_blk_mem_gen_0_0/top_block_blk_mem_gen_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block_blk_mem_gen_0_0 || ORIG_REF_NAME==top_block_blk_mem_gen_0_0} -quiet] -quiet

# IP: bd/top_block/ip/top_block_axi_bram_ctrl_1_0/top_block_axi_bram_ctrl_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block_axi_bram_ctrl_1_0 || ORIG_REF_NAME==top_block_axi_bram_ctrl_1_0} -quiet] -quiet

# IP: bd/top_block/ip/top_block_axi_iic_0_0/top_block_axi_iic_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block_axi_iic_0_0 || ORIG_REF_NAME==top_block_axi_iic_0_0} -quiet] -quiet

# IP: bd/top_block/ip/top_block_iobuf_vhdl_0_0/top_block_iobuf_vhdl_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block_iobuf_vhdl_0_0 || ORIG_REF_NAME==top_block_iobuf_vhdl_0_0} -quiet] -quiet

# IP: bd/top_block/ip/top_block_iobuf_vhdl_1_0/top_block_iobuf_vhdl_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block_iobuf_vhdl_1_0 || ORIG_REF_NAME==top_block_iobuf_vhdl_1_0} -quiet] -quiet

# IP: bd/top_block/ip/top_block_I2C_Controller_v1_0_0_1/top_block_I2C_Controller_v1_0_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block_I2C_Controller_v1_0_0_1 || ORIG_REF_NAME==top_block_I2C_Controller_v1_0_0_1} -quiet] -quiet

# IP: bd/top_block/ip/top_block_init_i2c_v1_0_0_0/top_block_init_i2c_v1_0_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block_init_i2c_v1_0_0_0 || ORIG_REF_NAME==top_block_init_i2c_v1_0_0_0} -quiet] -quiet

# IP: bd/top_block/ip/top_block_xlconstant_0_3/top_block_xlconstant_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block_xlconstant_0_3 || ORIG_REF_NAME==top_block_xlconstant_0_3} -quiet] -quiet

# IP: bd/top_block/ip/top_block_xpm_cdc_gen_0_1/top_block_xpm_cdc_gen_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block_xpm_cdc_gen_0_1 || ORIG_REF_NAME==top_block_xpm_cdc_gen_0_1} -quiet] -quiet

# IP: bd/top_block/ip/top_block_das_rx_0_0/top_block_das_rx_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block_das_rx_0_0 || ORIG_REF_NAME==top_block_das_rx_0_0} -quiet] -quiet

# IP: bd/top_block/ip/top_block_trigger_manager_0_0/top_block_trigger_manager_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block_trigger_manager_0_0 || ORIG_REF_NAME==top_block_trigger_manager_0_0} -quiet] -quiet

# IP: bd/top_block/ip/top_block_event_builder_v0_1_0_1/top_block_event_builder_v0_1_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block_event_builder_v0_1_0_1 || ORIG_REF_NAME==top_block_event_builder_v0_1_0_1} -quiet] -quiet

# IP: bd/top_block/ip/top_block_data_processor_0_0/top_block_data_processor_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block_data_processor_0_0 || ORIG_REF_NAME==top_block_data_processor_0_0} -quiet] -quiet

# IP: bd/top_block/ip/top_block_xpm_afifo_wrapper_0_0/top_block_xpm_afifo_wrapper_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block_xpm_afifo_wrapper_0_0 || ORIG_REF_NAME==top_block_xpm_afifo_wrapper_0_0} -quiet] -quiet

# IP: bd/top_block/ip/top_block_xpm_afifo_wrapper_1_0/top_block_xpm_afifo_wrapper_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block_xpm_afifo_wrapper_1_0 || ORIG_REF_NAME==top_block_xpm_afifo_wrapper_1_0} -quiet] -quiet

# IP: bd/top_block/ip/top_block_xpm_afifo_wrapper_2_0/top_block_xpm_afifo_wrapper_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block_xpm_afifo_wrapper_2_0 || ORIG_REF_NAME==top_block_xpm_afifo_wrapper_2_0} -quiet] -quiet

# IP: bd/top_block/ip/top_block_xpm_async_fifo_wrapp_0_0/top_block_xpm_async_fifo_wrapp_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block_xpm_async_fifo_wrapp_0_0 || ORIG_REF_NAME==top_block_xpm_async_fifo_wrapp_0_0} -quiet] -quiet

# IP: bd/top_block/ip/top_block_xlconcat_1_2/top_block_xlconcat_1_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block_xlconcat_1_2 || ORIG_REF_NAME==top_block_xlconcat_1_2} -quiet] -quiet

# IP: bd/top_block/ip/top_block_util_vector_logic_0_3/top_block_util_vector_logic_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block_util_vector_logic_0_3 || ORIG_REF_NAME==top_block_util_vector_logic_0_3} -quiet] -quiet

# IP: bd/top_block/ip/top_block_util_vector_logic_0_7/top_block_util_vector_logic_0_7.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block_util_vector_logic_0_7 || ORIG_REF_NAME==top_block_util_vector_logic_0_7} -quiet] -quiet

# IP: bd/top_block/ip/top_block_util_vector_logic_0_8/top_block_util_vector_logic_0_8.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block_util_vector_logic_0_8 || ORIG_REF_NAME==top_block_util_vector_logic_0_8} -quiet] -quiet

# IP: bd/top_block/ip/top_block_util_vector_logic_0_9/top_block_util_vector_logic_0_9.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block_util_vector_logic_0_9 || ORIG_REF_NAME==top_block_util_vector_logic_0_9} -quiet] -quiet

# IP: bd/top_block/ip/top_block_xlslice_0_1/top_block_xlslice_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block_xlslice_0_1 || ORIG_REF_NAME==top_block_xlslice_0_1} -quiet] -quiet

# IP: bd/top_block/ip/top_block_xlslice_0_2/top_block_xlslice_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block_xlslice_0_2 || ORIG_REF_NAME==top_block_xlslice_0_2} -quiet] -quiet

# IP: bd/top_block/ip/top_block_xlslice_0_3/top_block_xlslice_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block_xlslice_0_3 || ORIG_REF_NAME==top_block_xlslice_0_3} -quiet] -quiet

# IP: bd/top_block/ip/top_block_xlslice_0_0/top_block_xlslice_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block_xlslice_0_0 || ORIG_REF_NAME==top_block_xlslice_0_0} -quiet] -quiet

# IP: bd/top_block/ip/top_block_xlconcat_0_2/top_block_xlconcat_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block_xlconcat_0_2 || ORIG_REF_NAME==top_block_xlconcat_0_2} -quiet] -quiet

# IP: bd/top_block/ip/top_block_xlconcat_0_1/top_block_xlconcat_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block_xlconcat_0_1 || ORIG_REF_NAME==top_block_xlconcat_0_1} -quiet] -quiet

# IP: bd/top_block/ip/top_block_data_sender_v1_0_0_0/top_block_data_sender_v1_0_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block_data_sender_v1_0_0_0 || ORIG_REF_NAME==top_block_data_sender_v1_0_0_0} -quiet] -quiet

# IP: bd/top_block/ip/top_block_axis_data_fifo_0_0/top_block_axis_data_fifo_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block_axis_data_fifo_0_0 || ORIG_REF_NAME==top_block_axis_data_fifo_0_0} -quiet] -quiet

# IP: bd/top_block/ip/top_block_mii_initializer_0_0/top_block_mii_initializer_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block_mii_initializer_0_0 || ORIG_REF_NAME==top_block_mii_initializer_0_0} -quiet] -quiet

# IP: bd/top_block/ip/top_block_util_vector_logic_0_0/top_block_util_vector_logic_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block_util_vector_logic_0_0 || ORIG_REF_NAME==top_block_util_vector_logic_0_0} -quiet] -quiet

# IP: bd/top_block/ip/top_block_util_vector_logic_1_0/top_block_util_vector_logic_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block_util_vector_logic_1_0 || ORIG_REF_NAME==top_block_util_vector_logic_1_0} -quiet] -quiet

# IP: bd/top_block/ip/top_block_util_vector_logic_2_0/top_block_util_vector_logic_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block_util_vector_logic_2_0 || ORIG_REF_NAME==top_block_util_vector_logic_2_0} -quiet] -quiet

# IP: bd/top_block/ip/top_block_util_vector_logic_1_1/top_block_util_vector_logic_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block_util_vector_logic_1_1 || ORIG_REF_NAME==top_block_util_vector_logic_1_1} -quiet] -quiet

# IP: bd/top_block/ip/top_block_util_vector_logic_0_1/top_block_util_vector_logic_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block_util_vector_logic_0_1 || ORIG_REF_NAME==top_block_util_vector_logic_0_1} -quiet] -quiet

# IP: bd/top_block/ip/top_block_util_vector_logic_1_2/top_block_util_vector_logic_1_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block_util_vector_logic_1_2 || ORIG_REF_NAME==top_block_util_vector_logic_1_2} -quiet] -quiet

# IP: bd/top_block/ip/top_block_util_vector_logic_2_1/top_block_util_vector_logic_2_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block_util_vector_logic_2_1 || ORIG_REF_NAME==top_block_util_vector_logic_2_1} -quiet] -quiet

# IP: bd/top_block/ip/top_block_util_vector_logic_3_0/top_block_util_vector_logic_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block_util_vector_logic_3_0 || ORIG_REF_NAME==top_block_util_vector_logic_3_0} -quiet] -quiet

# IP: bd/top_block/ip/top_block_xlconstant_0_0/top_block_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block_xlconstant_0_0 || ORIG_REF_NAME==top_block_xlconstant_0_0} -quiet] -quiet

# IP: bd/top_block/ip/top_block_xlconstant_0_1/top_block_xlconstant_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block_xlconstant_0_1 || ORIG_REF_NAME==top_block_xlconstant_0_1} -quiet] -quiet

# IP: bd/top_block/ip/top_block_xlconstant_1_2/top_block_xlconstant_1_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block_xlconstant_1_2 || ORIG_REF_NAME==top_block_xlconstant_1_2} -quiet] -quiet

# IP: bd/top_block/ip/top_block_xlconstant_1_3/top_block_xlconstant_1_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block_xlconstant_1_3 || ORIG_REF_NAME==top_block_xlconstant_1_3} -quiet] -quiet

# IP: bd/top_block/ip/top_block_RESET_INST_0_0/top_block_RESET_INST_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block_RESET_INST_0_0 || ORIG_REF_NAME==top_block_RESET_INST_0_0} -quiet] -quiet

# IP: bd/top_block/ip/top_block_gig_ethernet_pcs_pma_0_0/top_block_gig_ethernet_pcs_pma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block_gig_ethernet_pcs_pma_0_0 || ORIG_REF_NAME==top_block_gig_ethernet_pcs_pma_0_0} -quiet] -quiet

# IP: ip/gig_ethernet_pcs_pma_0_2/gig_ethernet_pcs_pma_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==gig_ethernet_pcs_pma_0 || ORIG_REF_NAME==gig_ethernet_pcs_pma_0} -quiet] -quiet

# IP: ip/gig_ethernet_pcs_pma_0_gt/gig_ethernet_pcs_pma_0_gt.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==gig_ethernet_pcs_pma_0_gt || ORIG_REF_NAME==gig_ethernet_pcs_pma_0_gt} -quiet] -quiet

# IP: bd/top_block/ip/top_block_fakernet_top_0_0/top_block_fakernet_top_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block_fakernet_top_0_0 || ORIG_REF_NAME==top_block_fakernet_top_0_0} -quiet] -quiet

# IP: bd/top_block/ip/top_block_reg_switch_0_0/top_block_reg_switch_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block_reg_switch_0_0 || ORIG_REF_NAME==top_block_reg_switch_0_0} -quiet] -quiet

# IP: bd/top_block/ip/top_block_data_receiver_v1_0_0_0/top_block_data_receiver_v1_0_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block_data_receiver_v1_0_0_0 || ORIG_REF_NAME==top_block_data_receiver_v1_0_0_0} -quiet] -quiet

# IP: bd/top_block/ip/top_block_native_to_axi_lite_v_0_0/top_block_native_to_axi_lite_v_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block_native_to_axi_lite_v_0_0 || ORIG_REF_NAME==top_block_native_to_axi_lite_v_0_0} -quiet] -quiet

# IP: bd/top_block/ip/top_block_data_gen_user_0_0/top_block_data_gen_user_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block_data_gen_user_0_0 || ORIG_REF_NAME==top_block_data_gen_user_0_0} -quiet] -quiet

# IP: bd/top_block/ip/top_block_xlconcat_0_0/top_block_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block_xlconcat_0_0 || ORIG_REF_NAME==top_block_xlconcat_0_0} -quiet] -quiet

# IP: bd/top_block/ip/top_block_util_ds_buf_0_1/top_block_util_ds_buf_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block_util_ds_buf_0_1 || ORIG_REF_NAME==top_block_util_ds_buf_0_1} -quiet] -quiet

# IP: bd/top_block/ip/top_block_clk_wiz_1_0/top_block_clk_wiz_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block_clk_wiz_1_0 || ORIG_REF_NAME==top_block_clk_wiz_1_0} -quiet] -quiet

# IP: bd/top_block/ip/top_block_clk_wiz_0_0/top_block_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block_clk_wiz_0_0 || ORIG_REF_NAME==top_block_clk_wiz_0_0} -quiet] -quiet

# IP: bd/top_block/ip/top_block_delay_adjust_init_v1_0_0/top_block_delay_adjust_init_v1_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block_delay_adjust_init_v1_0_0 || ORIG_REF_NAME==top_block_delay_adjust_init_v1_0_0} -quiet] -quiet

# IP: bd/top_block/ip/top_block_idelay_top_v2_0_0/top_block_idelay_top_v2_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block_idelay_top_v2_0_0 || ORIG_REF_NAME==top_block_idelay_top_v2_0_0} -quiet] -quiet

# IP: bd/top_block/ip/top_block_TRG_MODULE_0_0/top_block_TRG_MODULE_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block_TRG_MODULE_0_0 || ORIG_REF_NAME==top_block_TRG_MODULE_0_0} -quiet] -quiet

# IP: bd/top_block/ip/top_block_util_ds_buf_1_1/top_block_util_ds_buf_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block_util_ds_buf_1_1 || ORIG_REF_NAME==top_block_util_ds_buf_1_1} -quiet] -quiet

# IP: bd/top_block/ip/top_block_SAMPA_TRG_EN_v1_0_0_0/top_block_SAMPA_TRG_EN_v1_0_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block_SAMPA_TRG_EN_v1_0_0_0 || ORIG_REF_NAME==top_block_SAMPA_TRG_EN_v1_0_0_0} -quiet] -quiet

# IP: bd/top_block/ip/top_block_SAMPA_PON_v1_0_0_0/top_block_SAMPA_PON_v1_0_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block_SAMPA_PON_v1_0_0_0 || ORIG_REF_NAME==top_block_SAMPA_PON_v1_0_0_0} -quiet] -quiet

# IP: bd/top_block/ip/top_block_clk_wiz_2_0/top_block_clk_wiz_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block_clk_wiz_2_0 || ORIG_REF_NAME==top_block_clk_wiz_2_0} -quiet] -quiet

# IP: bd/top_block/ip/top_block_xlconstant_1_4/top_block_xlconstant_1_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block_xlconstant_1_4 || ORIG_REF_NAME==top_block_xlconstant_1_4} -quiet] -quiet

# IP: bd/top_block/ip/top_block_util_ds_buf_4_1/top_block_util_ds_buf_4_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block_util_ds_buf_4_1 || ORIG_REF_NAME==top_block_util_ds_buf_4_1} -quiet] -quiet

# IP: bd/top_block/ip/top_block_util_ds_buf_2_0/top_block_util_ds_buf_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block_util_ds_buf_2_0 || ORIG_REF_NAME==top_block_util_ds_buf_2_0} -quiet] -quiet

# IP: bd/top_block/ip/top_block_xlconcat_2_1/top_block_xlconcat_2_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block_xlconcat_2_1 || ORIG_REF_NAME==top_block_xlconcat_2_1} -quiet] -quiet

# IP: bd/top_block/ip/top_block_util_vector_logic_1_3/top_block_util_vector_logic_1_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block_util_vector_logic_1_3 || ORIG_REF_NAME==top_block_util_vector_logic_1_3} -quiet] -quiet

# IP: bd/top_block/ip/top_block_util_ds_buf_3_2/top_block_util_ds_buf_3_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block_util_ds_buf_3_2 || ORIG_REF_NAME==top_block_util_ds_buf_3_2} -quiet] -quiet

# IP: bd/top_block/ip/top_block_xbar_1/top_block_xbar_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block_xbar_1 || ORIG_REF_NAME==top_block_xbar_1} -quiet] -quiet

# IP: bd/top_block/ip/top_block_axi_mem_intercon_3/top_block_axi_mem_intercon_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block_axi_mem_intercon_3 || ORIG_REF_NAME==top_block_axi_mem_intercon_3} -quiet] -quiet

# IP: bd/top_block/ip/top_block_m00_data_fifo_0/top_block_m00_data_fifo_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_block_m00_data_fifo_0 || ORIG_REF_NAME==top_block_m00_data_fifo_0} -quiet] -quiet

# XDC: ip/gig_ethernet_pcs_pma_0_gt/synth/gig_ethernet_pcs_pma_0_gt_ooc.xdc

# XDC: ip/gig_ethernet_pcs_pma_0_gt/synth/gig_ethernet_pcs_pma_0_gt.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==gig_ethernet_pcs_pma_0_gt || ORIG_REF_NAME==gig_ethernet_pcs_pma_0_gt} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: ip/gig_ethernet_pcs_pma_0_gt/synth/gig_ethernet_pcs_pma_0_gt_ooc.xdc

# XDC: ip/gig_ethernet_pcs_pma_0_gt/synth/gig_ethernet_pcs_pma_0_gt.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==gig_ethernet_pcs_pma_0_gt || ORIG_REF_NAME==gig_ethernet_pcs_pma_0_gt} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/nagafusa/work/spadi/Fakernet/SAMIDARE/samidare.gen/sources_1/bd/top_block/top_block_ooc.xdc
