set_property SRC_FILE_INFO {cfile:/home/nagafusa/work/spadi/Fakernet/SAMIDARE/samidare.srcs/constrs_1/new/GTH.xdc rfile:../../../samidare.srcs/constrs_1/new/GTH.xdc id:1} [current_design]
set_property SRC_FILE_INFO {cfile:/home/nagafusa/work/spadi/Fakernet/SAMIDARE/samidare.srcs/constrs_1/new/main_io.xdc rfile:../../../samidare.srcs/constrs_1/new/main_io.xdc id:2} [current_design]
set_property SRC_FILE_INFO {cfile:/home/nagafusa/work/spadi/Fakernet/SAMIDARE/samidare.srcs/constrs_1/new/samidare_io.xdc rfile:../../../samidare.srcs/constrs_1/new/samidare_io.xdc id:3} [current_design]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H5 [get_ports SFP_CLK_N]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H6 [get_ports SFP_CLK_P]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F2 [get_ports SFP0RXP]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F1 [get_ports SFP0RXN]
set_property src_info {type:XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E4 [get_ports SFP0TXP]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E3 [get_ports SFP0TXN]
set_property src_info {type:XDC file:2 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L17 [get_ports BASECLK]
set_property src_info {type:XDC file:2 line:31 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y20 [get_ports {SO0P[0]}]
set_property src_info {type:XDC file:2 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y21 [get_ports {SO0N[0]}]
set_property src_info {type:XDC file:2 line:34 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V19 [get_ports {SO0P[1]}]
set_property src_info {type:XDC file:2 line:35 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W19 [get_ports {SO0N[1]}]
set_property src_info {type:XDC file:2 line:36 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U17 [get_ports {SO0P[2]}]
set_property src_info {type:XDC file:2 line:37 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V17 [get_ports {SO0N[2]}]
set_property src_info {type:XDC file:2 line:38 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W17 [get_ports {SO0P[3]}]
set_property src_info {type:XDC file:2 line:39 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W18 [get_ports {SO0N[3]}]
set_property src_info {type:XDC file:2 line:40 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y18 [get_ports {SO0P[4]}]
set_property src_info {type:XDC file:2 line:41 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y19 [get_ports {SO0N[4]}]
set_property src_info {type:XDC file:2 line:42 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y14 [get_ports {SO0P[5]}]
set_property src_info {type:XDC file:2 line:43 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y15 [get_ports {SO0N[5]}]
set_property src_info {type:XDC file:2 line:44 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W16 [get_ports {SO0P[6]}]
set_property src_info {type:XDC file:2 line:45 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y16 [get_ports {SO0N[6]}]
set_property src_info {type:XDC file:2 line:46 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U18 [get_ports {SO0P[7]}]
set_property src_info {type:XDC file:2 line:47 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U19 [get_ports {SO0N[7]}]
set_property src_info {type:XDC file:2 line:48 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V14 [get_ports {SO0P[8]}]
set_property src_info {type:XDC file:2 line:49 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W14 [get_ports {SO0N[8]}]
set_property src_info {type:XDC file:2 line:50 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T17 [get_ports {SO0P[9]}]
set_property src_info {type:XDC file:2 line:51 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T18 [get_ports {SO0N[9]}]
set_property src_info {type:XDC file:2 line:52 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W13 [get_ports {SO0P[10]}]
set_property src_info {type:XDC file:2 line:53 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y13 [get_ports {SO0N[10]}]
set_property src_info {type:XDC file:2 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M19 [get_ports {SO1P[0]}]
set_property src_info {type:XDC file:2 line:58 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M20 [get_ports {SO1N[0]}]
set_property src_info {type:XDC file:2 line:59 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N21 [get_ports {SO1P[1]}]
set_property src_info {type:XDC file:2 line:60 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N22 [get_ports {SO1N[1]}]
set_property src_info {type:XDC file:2 line:61 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R16 [get_ports {SO1P[2]}]
set_property src_info {type:XDC file:2 line:62 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P16 [get_ports {SO1N[2]}]
set_property src_info {type:XDC file:2 line:63 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P21 [get_ports {SO1P[3]}]
set_property src_info {type:XDC file:2 line:64 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P22 [get_ports {SO1N[3]}]
set_property src_info {type:XDC file:2 line:65 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N16 [get_ports {SO1P[4]}]
set_property src_info {type:XDC file:2 line:66 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N17 [get_ports {SO1N[4]}]
set_property src_info {type:XDC file:2 line:68 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R18 [get_ports {SO1P[5]}]
set_property src_info {type:XDC file:2 line:69 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P18 [get_ports {SO1N[5]}]
set_property src_info {type:XDC file:2 line:70 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T21 [get_ports {SO1P[6]}]
set_property src_info {type:XDC file:2 line:71 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R21 [get_ports {SO1N[6]}]
set_property src_info {type:XDC file:2 line:72 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K20 [get_ports {SO1P[7]}]
set_property src_info {type:XDC file:2 line:73 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K21 [get_ports {SO1N[7]}]
set_property src_info {type:XDC file:2 line:74 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P19 [get_ports {SO1P[8]}]
set_property src_info {type:XDC file:2 line:75 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N19 [get_ports {SO1N[8]}]
set_property src_info {type:XDC file:2 line:77 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M17 [get_ports {SO1P[9]}]
set_property src_info {type:XDC file:2 line:78 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M18 [get_ports {SO1N[9]}]
set_property src_info {type:XDC file:2 line:80 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R19 [get_ports {SO1P[10]}]
set_property src_info {type:XDC file:2 line:81 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R20 [get_ports {SO1N[10]}]
set_property src_info {type:XDC file:2 line:86 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G19 [get_ports {SO2P[0]}]
set_property src_info {type:XDC file:2 line:87 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G20 [get_ports {SO2N[0]}]
set_property src_info {type:XDC file:2 line:88 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G18 [get_ports {SO2P[1]}]
set_property src_info {type:XDC file:2 line:89 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F18 [get_ports {SO2N[1]}]
set_property src_info {type:XDC file:2 line:90 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G17 [get_ports {SO2P[2]}]
set_property src_info {type:XDC file:2 line:91 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F17 [get_ports {SO2N[2]}]
set_property src_info {type:XDC file:2 line:92 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H16 [get_ports {SO2P[3]}]
set_property src_info {type:XDC file:2 line:93 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H17 [get_ports {SO2N[3]}]
set_property src_info {type:XDC file:2 line:94 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H20 [get_ports {SO2P[4]}]
set_property src_info {type:XDC file:2 line:95 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H21 [get_ports {SO2N[4]}]
set_property src_info {type:XDC file:2 line:96 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K18 [get_ports {SO2P[5]}]
set_property src_info {type:XDC file:2 line:97 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K19 [get_ports {SO2N[5]}]
set_property src_info {type:XDC file:2 line:98 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K16 [get_ports {SO2P[6]}]
set_property src_info {type:XDC file:2 line:99 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J16 [get_ports {SO2N[6]}]
set_property src_info {type:XDC file:2 line:100 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M22 [get_ports {SO2P[7]}]
set_property src_info {type:XDC file:2 line:101 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L22 [get_ports {SO2N[7]}]
set_property src_info {type:XDC file:2 line:102 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J18 [get_ports {SO2P[8]}]
set_property src_info {type:XDC file:2 line:103 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J19 [get_ports {SO2N[8]}]
set_property src_info {type:XDC file:2 line:104 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H22 [get_ports {SO2P[9]}]
set_property src_info {type:XDC file:2 line:105 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G22 [get_ports {SO2N[9]}]
set_property src_info {type:XDC file:2 line:106 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L20 [get_ports {SO2P[10]}]
set_property src_info {type:XDC file:2 line:107 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L21 [get_ports {SO2N[10]}]
set_property src_info {type:XDC file:2 line:112 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G12 [get_ports {SO3P[0]}]
set_property src_info {type:XDC file:2 line:113 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F12 [get_ports {SO3N[0]}]
set_property src_info {type:XDC file:2 line:114 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C15 [get_ports {SO3P[1]}]
set_property src_info {type:XDC file:2 line:115 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B15 [get_ports {SO3N[1]}]
set_property src_info {type:XDC file:2 line:116 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D17 [get_ports {SO3P[2]}]
set_property src_info {type:XDC file:2 line:117 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C17 [get_ports {SO3N[2]}]
set_property src_info {type:XDC file:2 line:118 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E18 [get_ports {SO3P[3]}]
set_property src_info {type:XDC file:2 line:119 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D18 [get_ports {SO3N[3]}]
set_property src_info {type:XDC file:2 line:120 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E13 [get_ports {SO3P[4]}]
set_property src_info {type:XDC file:2 line:121 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E14 [get_ports {SO3N[4]}]
set_property src_info {type:XDC file:2 line:122 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F15 [get_ports {SO3P[5]}]
set_property src_info {type:XDC file:2 line:123 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F16 [get_ports {SO3N[5]}]
set_property src_info {type:XDC file:2 line:124 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C20 [get_ports {SO3P[6]}]
set_property src_info {type:XDC file:2 line:125 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C21 [get_ports {SO3N[6]}]
set_property src_info {type:XDC file:2 line:126 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D13 [get_ports {SO3P[7]}]
set_property src_info {type:XDC file:2 line:127 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D14 [get_ports {SO3N[7]}]
set_property src_info {type:XDC file:2 line:128 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F20 [get_ports {SO3P[8]}]
set_property src_info {type:XDC file:2 line:129 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E20 [get_ports {SO3N[8]}]
set_property src_info {type:XDC file:2 line:130 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D12 [get_ports {SO3P[9]}]
set_property src_info {type:XDC file:2 line:131 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C12 [get_ports {SO3N[9]}]
set_property src_info {type:XDC file:2 line:132 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E19 [get_ports {SO3P[10]}]
set_property src_info {type:XDC file:2 line:133 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D19 [get_ports {SO3N[10]}]
set_property src_info {type:XDC file:2 line:147 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB17 [get_ports {HBTRG_P[0]}]
set_property src_info {type:XDC file:2 line:148 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB18 [get_ports {HBTRG_N[0]}]
set_property src_info {type:XDC file:2 line:149 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA18 [get_ports {BX_SYNC_TRG_P[0]}]
set_property src_info {type:XDC file:2 line:150 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA16 [get_ports {TRG_P[0]}]
set_property src_info {type:XDC file:2 line:151 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA17 [get_ports {TRG_N[0]}]
set_property src_info {type:XDC file:2 line:152 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T20 [get_ports {TRG_P[1]}]
set_property src_info {type:XDC file:2 line:153 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T22 [get_ports {TRG_P[2]}]
set_property src_info {type:XDC file:2 line:154 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C22 [get_ports {TRG_P[3]}]
set_property src_info {type:XDC file:2 line:155 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B22 [get_ports {TRG_N[3]}]
set_property src_info {type:XDC file:2 line:156 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB20 [get_ports {CLKSOIN_P[1]}]
set_property src_info {type:XDC file:2 line:157 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB21 [get_ports {CLKSOIN_N[1]}]
set_property src_info {type:XDC file:2 line:158 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA21 [get_ports {CLKSOIN_P[2]}]
set_property src_info {type:XDC file:2 line:159 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA22 [get_ports {CLKSOIN_N[2]}]
set_property src_info {type:XDC file:2 line:166 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D21 [get_ports {HRSTB_P[3]}]
set_property src_info {type:XDC file:2 line:167 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D22 [get_ports {HRSTB_N[3]}]
set_property src_info {type:XDC file:2 line:168 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V22 [get_ports {HRSTB_P[2]}]
set_property src_info {type:XDC file:2 line:169 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W22 [get_ports {HRSTB_N[2]}]
set_property src_info {type:XDC file:2 line:170 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V21 [get_ports {HRSTB_P[1]}]
set_property src_info {type:XDC file:2 line:171 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W21 [get_ports {HRSTB_N[1]}]
set_property src_info {type:XDC file:2 line:172 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB14 [get_ports {HRSTB_P[0]}]
set_property src_info {type:XDC file:2 line:173 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB15 [get_ports {HRSTB_N[0]}]
set_property src_info {type:XDC file:2 line:175 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F21 [get_ports {CLKSOIN_P[3]}]
set_property src_info {type:XDC file:2 line:176 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA13 [get_ports {CLKSOIN_P[0]}]
set_property src_info {type:XDC file:2 line:190 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B12 [get_ports {GPIOP[0]}]
set_property src_info {type:XDC file:2 line:191 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A13 [get_ports {GPION[0]}]
set_property src_info {type:XDC file:2 line:192 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C14 [get_ports {GPIOP[1]}]
set_property src_info {type:XDC file:2 line:193 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B14 [get_ports {GPION[1]}]
set_property src_info {type:XDC file:2 line:194 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A17 [get_ports {GPIOP[2]}]
set_property src_info {type:XDC file:2 line:195 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A18 [get_ports {GPION[2]}]
set_property src_info {type:XDC file:2 line:196 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A20 [get_ports {GPIOP[3]}]
set_property src_info {type:XDC file:2 line:197 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A21 [get_ports {GPION[3]}]
set_property src_info {type:XDC file:2 line:198 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A15 [get_ports {GPIOP[4]}]
set_property src_info {type:XDC file:2 line:199 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A16 [get_ports {GPION[4]}]
set_property src_info {type:XDC file:2 line:200 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D16 [get_ports {GPIOP[5]}]
set_property src_info {type:XDC file:2 line:201 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C16 [get_ports {GPION[5]}]
set_property src_info {type:XDC file:2 line:202 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B17 [get_ports {GPIOP[6]}]
set_property src_info {type:XDC file:2 line:203 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B18 [get_ports {GPION[6]}]
set_property src_info {type:XDC file:2 line:204 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C19 [get_ports {GPIOP[7]}]
set_property src_info {type:XDC file:2 line:205 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B19 [get_ports {GPION[7]}]
set_property src_info {type:XDC file:2 line:243 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA10 [get_ports PUSH_SW]
set_property src_info {type:XDC file:2 line:251 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA12 [get_ports SAMPA_EN_D]
set_property src_info {type:XDC file:2 line:252 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB12 [get_ports SAMPA_EN_A]
set_property src_info {type:XDC file:2 line:259 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V12 [get_ports {LED[0]}]
set_property src_info {type:XDC file:2 line:260 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U12 [get_ports {LED[1]}]
set_property src_info {type:XDC file:2 line:261 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V10 [get_ports {LED[2]}]
set_property src_info {type:XDC file:2 line:262 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V11 [get_ports {LED[3]}]
set_property src_info {type:XDC file:2 line:266 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB8 [get_ports {DIP_SW[0]}]
set_property src_info {type:XDC file:2 line:267 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA8 [get_ports {DIP_SW[1]}]
set_property src_info {type:XDC file:2 line:268 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB7 [get_ports {DIP_SW[2]}]
set_property src_info {type:XDC file:2 line:269 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB6 [get_ports {DIP_SW[3]}]
set_property src_info {type:XDC file:2 line:286 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C10 [get_ports S_I2C_SCL]
set_property src_info {type:XDC file:2 line:287 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A10 [get_ports S_I2C_SDA]
set_property src_info {type:XDC file:2 line:296 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B8 [get_ports {CLK_CFG[0]}]
set_property src_info {type:XDC file:2 line:297 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A8 [get_ports {CLK_CFG[1]}]
set_property src_info {type:XDC file:2 line:298 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B9 [get_ports {CLK_CFG[2]}]
set_property src_info {type:XDC file:2 line:299 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D11 [get_ports {CLK_CFG[3]}]
set_property src_info {type:XDC file:2 line:300 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A11 [get_ports {CLK_CFG[4]}]
set_property src_info {type:XDC file:2 line:301 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A12 [get_ports {CLK_CFG[5]}]
set_property src_info {type:XDC file:2 line:302 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B10 [get_ports {CLK_CFG[6]}]
set_property src_info {type:XDC file:2 line:305 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C9 [get_ports {POL[0]}]
set_property src_info {type:XDC file:2 line:306 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D8 [get_ports {CTS[0]}]
set_property src_info {type:XDC file:2 line:307 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C8 [get_ports {CG0[0]}]
set_property src_info {type:XDC file:2 line:308 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D9 [get_ports {CG1[0]}]
set_property src_info {type:XDC file:3 line:31 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_1/clk [get_nets [list u_ila_1_clk_out5]]
set_property src_info {type:XDC file:3 line:32 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_2/clk [get_nets [list u_ila_2_clk_out1]]
set_property src_info {type:XDC file:3 line:35 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe0 [get_nets [list {top_block_i/SO_receiver/idelay_top_v2_0/inst/gen_SO0[0].normal_inst.u_idelay_impl_SO0/decrement_count[0]} {top_block_i/SO_receiver/idelay_top_v2_0/inst/gen_SO0[0].normal_inst.u_idelay_impl_SO0/decrement_count[1]} {top_block_i/SO_receiver/idelay_top_v2_0/inst/gen_SO0[0].normal_inst.u_idelay_impl_SO0/decrement_count[2]} {top_block_i/SO_receiver/idelay_top_v2_0/inst/gen_SO0[0].normal_inst.u_idelay_impl_SO0/decrement_count[3]} {top_block_i/SO_receiver/idelay_top_v2_0/inst/gen_SO0[0].normal_inst.u_idelay_impl_SO0/decrement_count[4]} {top_block_i/SO_receiver/idelay_top_v2_0/inst/gen_SO0[0].normal_inst.u_idelay_impl_SO0/decrement_count[5]}]]
set_property src_info {type:XDC file:3 line:36 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe1 [get_nets [list {top_block_i/SO_receiver/idelay_top_v2_0/inst/gen_SO0[0].normal_inst.u_idelay_impl_SO0/elapsed_time_idelay[1]} {top_block_i/SO_receiver/idelay_top_v2_0/inst/gen_SO0[0].normal_inst.u_idelay_impl_SO0/elapsed_time_idelay[2]} {top_block_i/SO_receiver/idelay_top_v2_0/inst/gen_SO0[0].normal_inst.u_idelay_impl_SO0/elapsed_time_idelay[3]} {top_block_i/SO_receiver/idelay_top_v2_0/inst/gen_SO0[0].normal_inst.u_idelay_impl_SO0/elapsed_time_idelay[4]} {top_block_i/SO_receiver/idelay_top_v2_0/inst/gen_SO0[0].normal_inst.u_idelay_impl_SO0/elapsed_time_idelay[5]} {top_block_i/SO_receiver/idelay_top_v2_0/inst/gen_SO0[0].normal_inst.u_idelay_impl_SO0/elapsed_time_idelay[6]} {top_block_i/SO_receiver/idelay_top_v2_0/inst/gen_SO0[0].normal_inst.u_idelay_impl_SO0/elapsed_time_idelay[7]} {top_block_i/SO_receiver/idelay_top_v2_0/inst/gen_SO0[0].normal_inst.u_idelay_impl_SO0/elapsed_time_idelay[8]} {top_block_i/SO_receiver/idelay_top_v2_0/inst/gen_SO0[0].normal_inst.u_idelay_impl_SO0/elapsed_time_idelay[9]} {top_block_i/SO_receiver/idelay_top_v2_0/inst/gen_SO0[0].normal_inst.u_idelay_impl_SO0/elapsed_time_idelay[10]} {top_block_i/SO_receiver/idelay_top_v2_0/inst/gen_SO0[0].normal_inst.u_idelay_impl_SO0/elapsed_time_idelay[11]} {top_block_i/SO_receiver/idelay_top_v2_0/inst/gen_SO0[0].normal_inst.u_idelay_impl_SO0/elapsed_time_idelay[12]} {top_block_i/SO_receiver/idelay_top_v2_0/inst/gen_SO0[0].normal_inst.u_idelay_impl_SO0/elapsed_time_idelay[13]} {top_block_i/SO_receiver/idelay_top_v2_0/inst/gen_SO0[0].normal_inst.u_idelay_impl_SO0/elapsed_time_idelay[14]} {top_block_i/SO_receiver/idelay_top_v2_0/inst/gen_SO0[0].normal_inst.u_idelay_impl_SO0/elapsed_time_idelay[15]} {top_block_i/SO_receiver/idelay_top_v2_0/inst/gen_SO0[0].normal_inst.u_idelay_impl_SO0/elapsed_time_idelay[16]} {top_block_i/SO_receiver/idelay_top_v2_0/inst/gen_SO0[0].normal_inst.u_idelay_impl_SO0/elapsed_time_idelay[17]} {top_block_i/SO_receiver/idelay_top_v2_0/inst/gen_SO0[0].normal_inst.u_idelay_impl_SO0/elapsed_time_idelay[18]} {top_block_i/SO_receiver/idelay_top_v2_0/inst/gen_SO0[0].normal_inst.u_idelay_impl_SO0/elapsed_time_idelay[19]} {top_block_i/SO_receiver/idelay_top_v2_0/inst/gen_SO0[0].normal_inst.u_idelay_impl_SO0/elapsed_time_idelay[20]} {top_block_i/SO_receiver/idelay_top_v2_0/inst/gen_SO0[0].normal_inst.u_idelay_impl_SO0/elapsed_time_idelay[21]} {top_block_i/SO_receiver/idelay_top_v2_0/inst/gen_SO0[0].normal_inst.u_idelay_impl_SO0/elapsed_time_idelay[22]} {top_block_i/SO_receiver/idelay_top_v2_0/inst/gen_SO0[0].normal_inst.u_idelay_impl_SO0/elapsed_time_idelay[23]} {top_block_i/SO_receiver/idelay_top_v2_0/inst/gen_SO0[0].normal_inst.u_idelay_impl_SO0/elapsed_time_idelay[24]} {top_block_i/SO_receiver/idelay_top_v2_0/inst/gen_SO0[0].normal_inst.u_idelay_impl_SO0/elapsed_time_idelay[25]} {top_block_i/SO_receiver/idelay_top_v2_0/inst/gen_SO0[0].normal_inst.u_idelay_impl_SO0/elapsed_time_idelay[26]} {top_block_i/SO_receiver/idelay_top_v2_0/inst/gen_SO0[0].normal_inst.u_idelay_impl_SO0/elapsed_time_idelay[27]} {top_block_i/SO_receiver/idelay_top_v2_0/inst/gen_SO0[0].normal_inst.u_idelay_impl_SO0/elapsed_time_idelay[28]} {top_block_i/SO_receiver/idelay_top_v2_0/inst/gen_SO0[0].normal_inst.u_idelay_impl_SO0/elapsed_time_idelay[29]} {top_block_i/SO_receiver/idelay_top_v2_0/inst/gen_SO0[0].normal_inst.u_idelay_impl_SO0/elapsed_time_idelay[30]} {top_block_i/SO_receiver/idelay_top_v2_0/inst/gen_SO0[0].normal_inst.u_idelay_impl_SO0/elapsed_time_idelay[31]}]]
set_property src_info {type:XDC file:3 line:37 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe2 [get_nets [list {top_block_i/SO_receiver/idelay_top_v2_0/inst/gen_SO0[0].normal_inst.u_idelay_impl_SO0/idle_patt_count_reg[0]} {top_block_i/SO_receiver/idelay_top_v2_0/inst/gen_SO0[0].normal_inst.u_idelay_impl_SO0/idle_patt_count_reg[1]} {top_block_i/SO_receiver/idelay_top_v2_0/inst/gen_SO0[0].normal_inst.u_idelay_impl_SO0/idle_patt_count_reg[2]} {top_block_i/SO_receiver/idelay_top_v2_0/inst/gen_SO0[0].normal_inst.u_idelay_impl_SO0/idle_patt_count_reg[3]} {top_block_i/SO_receiver/idelay_top_v2_0/inst/gen_SO0[0].normal_inst.u_idelay_impl_SO0/idle_patt_count_reg[4]}]]
set_property src_info {type:XDC file:3 line:38 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe6 [get_nets [list {top_block_i/SO_receiver/idelay_top_v2_0/inst/aggregate_state_return[1]} {top_block_i/SO_receiver/idelay_top_v2_0/inst/aggregate_state_return[2]}]]
set_property src_info {type:XDC file:3 line:40 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe12 [get_nets [list {top_block_i/SO_receiver/idelay_top_v2_0/inst/gen_SO0[10].special_inst.u_idelay_impl_SO0/check_delay}]]
set_property src_info {type:XDC file:3 line:42 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe9 [get_nets [list {top_block_i/SO_receiver/idelay_top_v2_0/inst/gen_SO0[10].special_inst.u_idelay_impl_SO0/overall_state[0][0]} {top_block_i/SO_receiver/idelay_top_v2_0/inst/gen_SO0[10].special_inst.u_idelay_impl_SO0/overall_state[0][1]} {top_block_i/SO_receiver/idelay_top_v2_0/inst/gen_SO0[10].special_inst.u_idelay_impl_SO0/overall_state[0][2]}]]
set_property src_info {type:XDC file:3 line:43 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe14 [get_nets [list {top_block_i/SO_receiver/idelay_top_v2_0/inst/gen_SO0[10].special_inst.u_idelay_impl_SO0/init}]]
set_property src_info {type:XDC file:3 line:44 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe15 [get_nets [list top_block_i/SO_receiver/idelay_top_v2_0/inst/controller_inst/init]]
set_property src_info {type:XDC file:3 line:46 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe8 [get_nets [list {top_block_i/SO_receiver/idelay_top_v2_0/inst/gen_SO0[10].special_inst.u_idelay_impl_SO0/cycle_counter0_in[0]} {top_block_i/SO_receiver/idelay_top_v2_0/inst/gen_SO0[10].special_inst.u_idelay_impl_SO0/cycle_counter0_in[1]} {top_block_i/SO_receiver/idelay_top_v2_0/inst/gen_SO0[10].special_inst.u_idelay_impl_SO0/cycle_counter0_in[2]} {top_block_i/SO_receiver/idelay_top_v2_0/inst/gen_SO0[10].special_inst.u_idelay_impl_SO0/cycle_counter0_in[3]} {top_block_i/SO_receiver/idelay_top_v2_0/inst/gen_SO0[10].special_inst.u_idelay_impl_SO0/cycle_counter0_in[4]} {top_block_i/SO_receiver/idelay_top_v2_0/inst/gen_SO0[10].special_inst.u_idelay_impl_SO0/cycle_counter0_in[5]} {top_block_i/SO_receiver/idelay_top_v2_0/inst/gen_SO0[10].special_inst.u_idelay_impl_SO0/cycle_counter0_in[6]}]]
set_property src_info {type:XDC file:3 line:47 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe11 [get_nets [list {top_block_i/SO_receiver/idelay_top_v2_0/inst/gen_SO0[10].special_inst.u_idelay_impl_SO0/overall_state[0]} {top_block_i/SO_receiver/idelay_top_v2_0/inst/gen_SO0[10].special_inst.u_idelay_impl_SO0/overall_state[1]}]]
set_property src_info {type:XDC file:3 line:48 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe12 [get_nets [list {top_block_i/SO_receiver/idelay_top_v2_0/inst/gen_SO0[10].special_inst.u_idelay_impl_SO0/state[0]} {top_block_i/SO_receiver/idelay_top_v2_0/inst/gen_SO0[10].special_inst.u_idelay_impl_SO0/state[1]} {top_block_i/SO_receiver/idelay_top_v2_0/inst/gen_SO0[10].special_inst.u_idelay_impl_SO0/state[2]}]]
set_property src_info {type:XDC file:3 line:49 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe13 [get_nets [list {top_block_i/SO_receiver/idelay_top_v2_0/inst/gen_SO0[1].normal_inst.u_idelay_impl_SO0/SO0_out[0]}]]
set_property src_info {type:XDC file:3 line:50 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe20 [get_nets [list {top_block_i/SO_receiver/idelay_top_v2_0/inst/gen_SO0[10].special_inst.u_idelay_impl_SO0/trial_counter_reg_n_0_[0]}]]
set_property src_info {type:XDC file:3 line:51 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe21 [get_nets [list {top_block_i/SO_receiver/idelay_top_v2_0/inst/gen_SO0[10].special_inst.u_idelay_impl_SO0/trial_counter_reg_n_0_[1]}]]
set_property src_info {type:XDC file:3 line:52 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe22 [get_nets [list {top_block_i/SO_receiver/idelay_top_v2_0/inst/gen_SO0[10].special_inst.u_idelay_impl_SO0/trial_counter_reg_n_0_[2]}]]
set_property src_info {type:XDC file:3 line:53 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe23 [get_nets [list {top_block_i/SO_receiver/idelay_top_v2_0/inst/gen_SO0[10].special_inst.u_idelay_impl_SO0/trial_counter_reg_n_0_[3]}]]
set_property src_info {type:XDC file:3 line:54 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe24 [get_nets [list {top_block_i/SO_receiver/idelay_top_v2_0/inst/gen_SO0[10].special_inst.u_idelay_impl_SO0/trial_counter_reg_n_0_[4]}]]
set_property src_info {type:XDC file:3 line:55 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe25 [get_nets [list {top_block_i/SO_receiver/idelay_top_v2_0/inst/gen_SO0[10].special_inst.u_idelay_impl_SO0/trial_counter_reg_n_0_[5]}]]
set_property src_info {type:XDC file:3 line:56 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe26 [get_nets [list {top_block_i/SO_receiver/idelay_top_v2_0/inst/gen_SO0[10].special_inst.u_idelay_impl_SO0/trial_counter_reg_n_0_[6]}]]
set_property src_info {type:XDC file:3 line:57 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe27 [get_nets [list {top_block_i/SO_receiver/idelay_top_v2_0/inst/gen_SO0[10].special_inst.u_idelay_impl_SO0/trial_counter_reg_n_0_[7]}]]
set_property src_info {type:XDC file:3 line:59 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe19 [get_nets [list {top_block_i/SO_receiver/idelay_top_v2_0/inst/gen_SO0[10].special_inst.u_idelay_impl_SO0/delay_inc}]]
set_property src_info {type:XDC file:3 line:61 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe0 [get_nets [list {top_block_i/SO_receiver/idelay_top_v2_0/inst/gen_SO0[0].normal_inst.u_idelay_impl_SO0/SO0_out[0]}]]
set_property src_info {type:XDC file:3 line:62 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe18 [get_nets [list top_block_i/SO_receiver/idelay_top_v2_0/inst/controller_inst/trg]]
set_property src_info {type:XDC file:3 line:64 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe13 [get_nets [list {top_block_i/SO_receiver/idelay_top_v2_0/inst/gen_SO0[10].special_inst.u_idelay_impl_SO0/inc_ce}]]
set_property src_info {type:XDC file:3 line:66 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe18 [get_nets [list {top_block_i/SO_receiver/idelay_top_v2_0/inst/gen_SO0[10].special_inst.u_idelay_impl_SO0/ld}]]
set_property src_info {type:XDC file:3 line:68 export:INPUT save:INPUT read:READ} [current_design]
create_debug_core u_ila_0 ila
set_property src_info {type:XDC file:3 line:69 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:3 line:70 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:3 line:71 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:3 line:72 export:INPUT save:INPUT read:READ} [current_design]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:3 line:73 export:INPUT save:INPUT read:READ} [current_design]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:3 line:74 export:INPUT save:INPUT read:READ} [current_design]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:3 line:75 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:3 line:76 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:3 line:77 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
set_property src_info {type:XDC file:3 line:78 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/clk [get_nets [list top_block_i/clock_wrapper/clk_wiz_1/inst/clk_out1]]
set_property src_info {type:XDC file:3 line:79 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:3 line:80 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 4 [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:3 line:81 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe0 [get_nets [list {top_block_i/SO_receiver/idelay_top_v2_0/inst/gen_SO0[10].special_inst.u_idelay_impl_SO0/special_state[0]} {top_block_i/SO_receiver/idelay_top_v2_0/inst/gen_SO0[10].special_inst.u_idelay_impl_SO0/special_state[1]} {top_block_i/SO_receiver/idelay_top_v2_0/inst/gen_SO0[10].special_inst.u_idelay_impl_SO0/special_state[2]} {top_block_i/SO_receiver/idelay_top_v2_0/inst/gen_SO0[10].special_inst.u_idelay_impl_SO0/special_state[3]}]]
set_property src_info {type:XDC file:3 line:82 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:3 line:83 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:3 line:84 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 5 [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:3 line:85 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe1 [get_nets [list {top_block_i/SO_receiver/idelay_top_v2_0/inst/gen_SO0[10].special_inst.u_idelay_impl_SO0/max_cnt[0]} {top_block_i/SO_receiver/idelay_top_v2_0/inst/gen_SO0[10].special_inst.u_idelay_impl_SO0/max_cnt[1]} {top_block_i/SO_receiver/idelay_top_v2_0/inst/gen_SO0[10].special_inst.u_idelay_impl_SO0/max_cnt[2]} {top_block_i/SO_receiver/idelay_top_v2_0/inst/gen_SO0[10].special_inst.u_idelay_impl_SO0/max_cnt[3]} {top_block_i/SO_receiver/idelay_top_v2_0/inst/gen_SO0[10].special_inst.u_idelay_impl_SO0/max_cnt[4]}]]
set_property src_info {type:XDC file:3 line:86 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:3 line:87 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:3 line:88 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:3 line:89 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe2 [get_nets [list {top_block_i/SO_receiver/idelay_top_v2_0/inst/gen_SO0[10].special_inst.u_idelay_impl_SO0/aggregate_state_return[0]}]]
set_property src_info {type:XDC file:3 line:90 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:3 line:91 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property src_info {type:XDC file:3 line:92 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 4 [get_debug_ports u_ila_0/probe3]
set_property src_info {type:XDC file:3 line:93 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe3 [get_nets [list {top_block_i/SO_receiver/idelay_top_v2_0/inst/gen_SO0[10].special_inst.u_idelay_impl_SO0/ch0_special_state[0]} {top_block_i/SO_receiver/idelay_top_v2_0/inst/gen_SO0[10].special_inst.u_idelay_impl_SO0/ch0_special_state[1]} {top_block_i/SO_receiver/idelay_top_v2_0/inst/gen_SO0[10].special_inst.u_idelay_impl_SO0/ch0_special_state[2]} {top_block_i/SO_receiver/idelay_top_v2_0/inst/gen_SO0[10].special_inst.u_idelay_impl_SO0/ch0_special_state[3]}]]
set_property src_info {type:XDC file:3 line:94 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:3 line:95 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property src_info {type:XDC file:3 line:96 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 9 [get_debug_ports u_ila_0/probe4]
set_property src_info {type:XDC file:3 line:97 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe4 [get_nets [list {top_block_i/SO_receiver/idelay_top_v2_0/inst/gen_SO0[10].special_inst.u_idelay_impl_SO0/current_idelay[0]} {top_block_i/SO_receiver/idelay_top_v2_0/inst/gen_SO0[10].special_inst.u_idelay_impl_SO0/current_idelay[1]} {top_block_i/SO_receiver/idelay_top_v2_0/inst/gen_SO0[10].special_inst.u_idelay_impl_SO0/current_idelay[2]} {top_block_i/SO_receiver/idelay_top_v2_0/inst/gen_SO0[10].special_inst.u_idelay_impl_SO0/current_idelay[3]} {top_block_i/SO_receiver/idelay_top_v2_0/inst/gen_SO0[10].special_inst.u_idelay_impl_SO0/current_idelay[4]} {top_block_i/SO_receiver/idelay_top_v2_0/inst/gen_SO0[10].special_inst.u_idelay_impl_SO0/current_idelay[5]} {top_block_i/SO_receiver/idelay_top_v2_0/inst/gen_SO0[10].special_inst.u_idelay_impl_SO0/current_idelay[6]} {top_block_i/SO_receiver/idelay_top_v2_0/inst/gen_SO0[10].special_inst.u_idelay_impl_SO0/current_idelay[7]} {top_block_i/SO_receiver/idelay_top_v2_0/inst/gen_SO0[10].special_inst.u_idelay_impl_SO0/current_idelay[8]}]]
set_property src_info {type:XDC file:3 line:98 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:3 line:99 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property src_info {type:XDC file:3 line:100 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 9 [get_debug_ports u_ila_0/probe5]
set_property src_info {type:XDC file:3 line:101 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe5 [get_nets [list {top_block_i/SO_receiver/idelay_top_v2_0/inst/gen_SO0[10].special_inst.u_idelay_impl_SO0/check_delay[0]} {top_block_i/SO_receiver/idelay_top_v2_0/inst/gen_SO0[10].special_inst.u_idelay_impl_SO0/check_delay[1]} {top_block_i/SO_receiver/idelay_top_v2_0/inst/gen_SO0[10].special_inst.u_idelay_impl_SO0/check_delay[2]} {top_block_i/SO_receiver/idelay_top_v2_0/inst/gen_SO0[10].special_inst.u_idelay_impl_SO0/check_delay[3]} {top_block_i/SO_receiver/idelay_top_v2_0/inst/gen_SO0[10].special_inst.u_idelay_impl_SO0/check_delay[4]} {top_block_i/SO_receiver/idelay_top_v2_0/inst/gen_SO0[10].special_inst.u_idelay_impl_SO0/check_delay[5]} {top_block_i/SO_receiver/idelay_top_v2_0/inst/gen_SO0[10].special_inst.u_idelay_impl_SO0/check_delay[6]} {top_block_i/SO_receiver/idelay_top_v2_0/inst/gen_SO0[10].special_inst.u_idelay_impl_SO0/check_delay[7]} {top_block_i/SO_receiver/idelay_top_v2_0/inst/gen_SO0[10].special_inst.u_idelay_impl_SO0/check_delay[8]}]]
set_property src_info {type:XDC file:3 line:102 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:3 line:103 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property src_info {type:XDC file:3 line:104 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 11 [get_debug_ports u_ila_0/probe6]
set_property src_info {type:XDC file:3 line:105 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe6 [get_nets [list {top_block_i/SO_receiver/idelay_top_v2_0/SO3_out[0]} {top_block_i/SO_receiver/idelay_top_v2_0/SO3_out[1]} {top_block_i/SO_receiver/idelay_top_v2_0/SO3_out[2]} {top_block_i/SO_receiver/idelay_top_v2_0/SO3_out[3]} {top_block_i/SO_receiver/idelay_top_v2_0/SO3_out[4]} {top_block_i/SO_receiver/idelay_top_v2_0/SO3_out[5]} {top_block_i/SO_receiver/idelay_top_v2_0/SO3_out[6]} {top_block_i/SO_receiver/idelay_top_v2_0/SO3_out[7]} {top_block_i/SO_receiver/idelay_top_v2_0/SO3_out[8]} {top_block_i/SO_receiver/idelay_top_v2_0/SO3_out[9]} {top_block_i/SO_receiver/idelay_top_v2_0/SO3_out[10]}]]
set_property src_info {type:XDC file:3 line:106 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:3 line:107 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property src_info {type:XDC file:3 line:108 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 11 [get_debug_ports u_ila_0/probe7]
set_property src_info {type:XDC file:3 line:109 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe7 [get_nets [list {top_block_i/SO_receiver/idelay_top_v2_0/SO1_out[0]} {top_block_i/SO_receiver/idelay_top_v2_0/SO1_out[1]} {top_block_i/SO_receiver/idelay_top_v2_0/SO1_out[2]} {top_block_i/SO_receiver/idelay_top_v2_0/SO1_out[3]} {top_block_i/SO_receiver/idelay_top_v2_0/SO1_out[4]} {top_block_i/SO_receiver/idelay_top_v2_0/SO1_out[5]} {top_block_i/SO_receiver/idelay_top_v2_0/SO1_out[6]} {top_block_i/SO_receiver/idelay_top_v2_0/SO1_out[7]} {top_block_i/SO_receiver/idelay_top_v2_0/SO1_out[8]} {top_block_i/SO_receiver/idelay_top_v2_0/SO1_out[9]} {top_block_i/SO_receiver/idelay_top_v2_0/SO1_out[10]}]]
set_property src_info {type:XDC file:3 line:110 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:3 line:111 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property src_info {type:XDC file:3 line:112 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 2 [get_debug_ports u_ila_0/probe8]
set_property src_info {type:XDC file:3 line:113 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe8 [get_nets [list {top_block_i/SO_receiver/idelay_top_v2_0/inst/overall_state[0]} {top_block_i/SO_receiver/idelay_top_v2_0/inst/overall_state[1]}]]
set_property src_info {type:XDC file:3 line:114 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:3 line:115 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
set_property src_info {type:XDC file:3 line:116 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 2 [get_debug_ports u_ila_0/probe9]
set_property src_info {type:XDC file:3 line:117 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe9 [get_nets [list {top_block_i/SO_receiver/idelay_top_v2_0/overall_state[0]} {top_block_i/SO_receiver/idelay_top_v2_0/overall_state[1]}]]
set_property src_info {type:XDC file:3 line:118 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:3 line:119 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe10]
set_property src_info {type:XDC file:3 line:120 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 11 [get_debug_ports u_ila_0/probe10]
set_property src_info {type:XDC file:3 line:121 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe10 [get_nets [list {top_block_i/SO_receiver/idelay_top_v2_0/SO2_out[0]} {top_block_i/SO_receiver/idelay_top_v2_0/SO2_out[1]} {top_block_i/SO_receiver/idelay_top_v2_0/SO2_out[2]} {top_block_i/SO_receiver/idelay_top_v2_0/SO2_out[3]} {top_block_i/SO_receiver/idelay_top_v2_0/SO2_out[4]} {top_block_i/SO_receiver/idelay_top_v2_0/SO2_out[5]} {top_block_i/SO_receiver/idelay_top_v2_0/SO2_out[6]} {top_block_i/SO_receiver/idelay_top_v2_0/SO2_out[7]} {top_block_i/SO_receiver/idelay_top_v2_0/SO2_out[8]} {top_block_i/SO_receiver/idelay_top_v2_0/SO2_out[9]} {top_block_i/SO_receiver/idelay_top_v2_0/SO2_out[10]}]]
set_property src_info {type:XDC file:3 line:122 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:3 line:123 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe11]
set_property src_info {type:XDC file:3 line:124 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe11]
set_property src_info {type:XDC file:3 line:125 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe11 [get_nets [list {top_block_i/SO_receiver/idelay_top_v2_0/inst/gen_SO0[10].special_inst.u_idelay_impl_SO0/SO0_out[0]}]]
set_property src_info {type:XDC file:3 line:126 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:3 line:127 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe12]
set_property src_info {type:XDC file:3 line:128 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 11 [get_debug_ports u_ila_0/probe12]
set_property src_info {type:XDC file:3 line:129 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe12 [get_nets [list {top_block_i/SO_receiver/idelay_top_v2_0/SO0_out[0]} {top_block_i/SO_receiver/idelay_top_v2_0/SO0_out[1]} {top_block_i/SO_receiver/idelay_top_v2_0/SO0_out[2]} {top_block_i/SO_receiver/idelay_top_v2_0/SO0_out[3]} {top_block_i/SO_receiver/idelay_top_v2_0/SO0_out[4]} {top_block_i/SO_receiver/idelay_top_v2_0/SO0_out[5]} {top_block_i/SO_receiver/idelay_top_v2_0/SO0_out[6]} {top_block_i/SO_receiver/idelay_top_v2_0/SO0_out[7]} {top_block_i/SO_receiver/idelay_top_v2_0/SO0_out[8]} {top_block_i/SO_receiver/idelay_top_v2_0/SO0_out[9]} {top_block_i/SO_receiver/idelay_top_v2_0/SO0_out[10]}]]
set_property src_info {type:XDC file:3 line:130 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:3 line:131 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe13]
set_property src_info {type:XDC file:3 line:132 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 8 [get_debug_ports u_ila_0/probe13]
set_property src_info {type:XDC file:3 line:133 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe13 [get_nets [list {top_block_i/SO_receiver/idelay_top_v2_0/inst/gen_SO0[10].special_inst.u_idelay_impl_SO0/cycle_counter[0]} {top_block_i/SO_receiver/idelay_top_v2_0/inst/gen_SO0[10].special_inst.u_idelay_impl_SO0/cycle_counter[1]} {top_block_i/SO_receiver/idelay_top_v2_0/inst/gen_SO0[10].special_inst.u_idelay_impl_SO0/cycle_counter[2]} {top_block_i/SO_receiver/idelay_top_v2_0/inst/gen_SO0[10].special_inst.u_idelay_impl_SO0/cycle_counter[3]} {top_block_i/SO_receiver/idelay_top_v2_0/inst/gen_SO0[10].special_inst.u_idelay_impl_SO0/cycle_counter[4]} {top_block_i/SO_receiver/idelay_top_v2_0/inst/gen_SO0[10].special_inst.u_idelay_impl_SO0/cycle_counter[5]} {top_block_i/SO_receiver/idelay_top_v2_0/inst/gen_SO0[10].special_inst.u_idelay_impl_SO0/cycle_counter[6]} {top_block_i/SO_receiver/idelay_top_v2_0/inst/gen_SO0[10].special_inst.u_idelay_impl_SO0/cycle_counter[7]}]]
set_property src_info {type:XDC file:3 line:134 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:3 line:135 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe14]
set_property src_info {type:XDC file:3 line:136 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe14]
set_property src_info {type:XDC file:3 line:137 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe14 [get_nets [list {top_block_i/SO_receiver/idelay_top_v2_0/inst/gen_SO0[10].special_inst.u_idelay_impl_SO0/prev_data}]]
set_property src_info {type:XDC file:3 line:138 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:3 line:139 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe15]
set_property src_info {type:XDC file:3 line:140 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe15]
set_property src_info {type:XDC file:3 line:141 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe15 [get_nets [list {top_block_i/SO_receiver/idelay_top_v2_0/inst/gen_SO0[10].special_inst.u_idelay_impl_SO0/raw_data_out}]]
set_property src_info {type:XDC file:3 line:142 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:3 line:143 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe16]
set_property src_info {type:XDC file:3 line:144 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe16]
set_property src_info {type:XDC file:3 line:145 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe16 [get_nets [list top_block_i/SO_receiver/idelay_top_v2_0/reset]]
set_property src_info {type:XDC file:3 line:146 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:3 line:147 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe17]
set_property src_info {type:XDC file:3 line:148 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe17]
set_property src_info {type:XDC file:3 line:149 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe17 [get_nets [list top_block_i/SO_receiver/idelay_top_v2_0/trg]]
set_property src_info {type:XDC file:3 line:150 export:INPUT save:INPUT read:READ} [current_design]
create_debug_core u_ila_1 ila
set_property src_info {type:XDC file:3 line:151 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_1]
set_property src_info {type:XDC file:3 line:152 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_1]
set_property src_info {type:XDC file:3 line:153 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_1]
set_property src_info {type:XDC file:3 line:154 export:INPUT save:INPUT read:READ} [current_design]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_1]
set_property src_info {type:XDC file:3 line:155 export:INPUT save:INPUT read:READ} [current_design]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_1]
set_property src_info {type:XDC file:3 line:156 export:INPUT save:INPUT read:READ} [current_design]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_1]
set_property src_info {type:XDC file:3 line:157 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_1]
set_property src_info {type:XDC file:3 line:158 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_1]
set_property src_info {type:XDC file:3 line:159 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_1/clk]
set_property src_info {type:XDC file:3 line:160 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_1/clk [get_nets [list top_block_i/clock_wrapper/clk_wiz_0/inst/clk_out5]]
set_property src_info {type:XDC file:3 line:161 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe0]
set_property src_info {type:XDC file:3 line:162 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_1/probe0]
set_property src_info {type:XDC file:3 line:163 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_1/probe0 [get_nets [list top_block_i/SAMPA_PON_v1_0_0/inst/sampa_power_on]]
set_property src_info {type:XDC file:3 line:164 export:INPUT save:INPUT read:READ} [current_design]
create_debug_core u_ila_2 ila
set_property src_info {type:XDC file:3 line:165 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_2]
set_property src_info {type:XDC file:3 line:166 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_2]
set_property src_info {type:XDC file:3 line:167 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_2]
set_property src_info {type:XDC file:3 line:168 export:INPUT save:INPUT read:READ} [current_design]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_2]
set_property src_info {type:XDC file:3 line:169 export:INPUT save:INPUT read:READ} [current_design]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_2]
set_property src_info {type:XDC file:3 line:170 export:INPUT save:INPUT read:READ} [current_design]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_2]
set_property src_info {type:XDC file:3 line:171 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_2]
set_property src_info {type:XDC file:3 line:172 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_2]
set_property src_info {type:XDC file:3 line:173 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_2/clk]
set_property src_info {type:XDC file:3 line:174 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_2/clk [get_nets [list top_block_i/clock_wrapper/clk_wiz_0/inst/clk_out1]]
set_property src_info {type:XDC file:3 line:175 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_2/probe0]
set_property src_info {type:XDC file:3 line:176 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_2/probe0]
set_property src_info {type:XDC file:3 line:177 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_2/probe0 [get_nets [list top_block_i/appUnit/data_processor_0/inst/trg]]
set_property src_info {type:XDC file:3 line:178 export:INPUT save:INPUT read:READ} [current_design]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:3 line:179 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:3 line:180 export:INPUT save:INPUT read:READ} [current_design]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:3 line:181 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port dbg_hub/clk [get_nets clk]
