# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/nagafusa/work/spadi/Fakernet/axi_iic_1_ex/axi_iic_1_ex.srcs/sources_1/ip/axi_iic_1/axi_iic_1.xci
# IP: The module: 'axi_iic_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/nagafusa/work/spadi/Fakernet/axi_iic_1_ex/axi_iic_1_ex.gen/sources_1/ip/axi_iic_1/axi_iic_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_iic_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/nagafusa/work/spadi/Fakernet/axi_iic_1_ex/axi_iic_1_ex.gen/sources_1/ip/axi_iic_1/axi_iic_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_iic_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/nagafusa/work/spadi/Fakernet/axi_iic_1_ex/axi_iic_1_ex.srcs/sources_1/ip/axi_iic_1/axi_iic_1.xci
# IP: The module: 'axi_iic_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/nagafusa/work/spadi/Fakernet/axi_iic_1_ex/axi_iic_1_ex.gen/sources_1/ip/axi_iic_1/axi_iic_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_iic_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/nagafusa/work/spadi/Fakernet/axi_iic_1_ex/axi_iic_1_ex.gen/sources_1/ip/axi_iic_1/axi_iic_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_iic_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
