
set_property SEVERITY {Warning} [get_drc_checks NSTD-1]
set_property SEVERITY {Warning} [get_drc_checks UCIO-1]

set_property BITSTREAM.CONFIG.UNUSEDPIN Pullup[current_design]

set_property IOSTANDARD LVDS [get_ports CLK254M_M0GC_P]
set_property IOSTANDARD LVDS [get_ports CLK254M_M0GC_N]
set_property PACKAGE_PIN E36 [get_ports CLK254M_M0GC_P]
set_property PACKAGE_PIN D36 [get_ports CLK254M_M0GC_N]
set_property IOSTANDARD LVDS [get_ports CLK254M_M1GC_P]
set_property IOSTANDARD LVDS [get_ports CLK254M_M1GC_N]
set_property PACKAGE_PIN AY35 [get_ports CLK254M_M1GC_P]
set_property PACKAGE_PIN AY36 [get_ports CLK254M_M1GC_N]

set_property IOSTANDARD LVDS  [get_ports CLKGTY_GC_P]
set_property IOSTANDARD LVDS  [get_ports CLKGTY_GC_N]
set_property PACKAGE_PIN AW14 [get_ports CLKGTY_GC_P]
set_property PACKAGE_PIN AW13 [get_ports CLKGTY_GC_N]
set_property IOSTANDARD LVDS  [get_ports CLKGTH_GC_P]
set_property IOSTANDARD LVDS  [get_ports CLKGTH_GC_N]
set_property PACKAGE_PIN AY13 [get_ports CLKGTH_GC_P]
set_property PACKAGE_PIN BA13 [get_ports CLKGTH_GC_N]

#set_property IOSTANDARD LVCMOS18 [get_ports PLL_GTH_RST]
#set_property PACKAGE_PIN BA9 [get_ports PLL_GTH_RST]
#set_property IOSTANDARD LVCMOS18 [get_ports PLL_GTY_RST]
#set_property PACKAGE_PIN BB19 [get_ports PLL_GTY_RST]
#set_property IOSTANDARD LVCMOS18 [get_ports PLL_GTH_SYNC]
#set_property PACKAGE_PIN AV18 [get_ports PLL_GTH_SYNC]
#set_property IOSTANDARD LVCMOS18 [get_ports PLL_GTY_SYNC]
#set_property PACKAGE_PIN BD19 [get_ports PLL_GTY_SYNC]
#set_property IOSTANDARD LVCMOS18 [get_ports PLL_GTH_CS]
#set_property PACKAGE_PIN BD11 [get_ports PLL_GTH_CS]
#set_property IOSTANDARD LVCMOS18 [get_ports PLL_GTY_CS]
#set_property PACKAGE_PIN BB15 [get_ports PLL_GTY_CS]
#set_property IOSTANDARD LVCMOS18 [get_ports PLL_GTH_SCL]
#set_property PACKAGE_PIN BF19 [get_ports PLL_GTH_SCL]
#set_property IOSTANDARD LVCMOS18 [get_ports PLL_GTY_SCL]
#set_property PACKAGE_PIN BC18 [get_ports PLL_GTY_SCL]

set_property IOSTANDARD LVCMOS18 [get_ports CLK50M]
set_property PACKAGE_PIN BA15 [get_ports CLK50M]

set_property IOSTANDARD LVCMOS18 [get_ports CLK127M_EXIN_SEL]
set_property PACKAGE_PIN BE13 [get_ports CLK127M_EXIN_SEL]
set_property IOSTANDARD LVCMOS18 [get_ports GTH_CLK_SEL]
set_property PACKAGE_PIN BD13 [get_ports GTH_CLK_SEL]
set_property IOSTANDARD LVCMOS18 [get_ports GTY_CLK_SEL]
set_property PACKAGE_PIN BF14 [get_ports GTY_CLK_SEL]
#set_property IOSTANDARD LVCMOS18 [get_ports PLL_GTY_SEL0]
#set_property PACKAGE_PIN BC9 [get_ports PLL_GTY_SEL0]
#set_property IOSTANDARD LVCMOS18 [get_ports PLL_GTY_SEL1]
#set_property PACKAGE_PIN BC19 [get_ports PLL_GTY_SEL1]
#set_property IOSTANDARD LVCMOS18 [get_ports PLL_GTH_SEL0]
#set_property PACKAGE_PIN BF18 [get_ports PLL_GTH_SEL0]
#set_property IOSTANDARD HSTL_I_18 [get_ports PLL_GTH_SEL1]
#set_property PACKAGE_PIN BA19 [get_ports PLL_GTH_SEL1]

#set_property IOSTANDARD LVCMOS18 [get_ports PLL_GTY_SDA]
#set_property PACKAGE_PIN BB9 [get_ports PLL_GTH_SDA]
#set_property IOSTANDARD LVCMOS18 [get_ports PLL_GTH_SDA]
#set_property PACKAGE_PIN BA8 [get_ports PLL_GTY_SDA]

#set_property IOSTANDARD LVCMOS18 [get_ports PLL_GTH_LD1]
#set_property PACKAGE_PIN AW18 [get_ports PLL_GTH_LD1]
#set_property IOSTANDARD LVCMOS18 [get_ports PLL_GTY_LD1]
#set_property PACKAGE_PIN AY20 [get_ports PLL_GTY_LD1]
#set_property IOSTANDARD LVCMOS18 [get_ports PLL_GTH_LD2]
#set_property PACKAGE_PIN AW20 [get_ports PLL_GTH_LD2]
#set_property IOSTANDARD LVCMOS18 [get_ports PLL_GTY_LD2]
#set_property PACKAGE_PIN BA18 [get_ports PLL_GTY_LD2]


#BE13 CLK127M_EXIN_SEL
#BC9 PLL_GTY_SEL0
#BC19 PLL_GTY_SEL1
#BF18 PLL_GTH_SEL0
#BA19 PLL_GTH_SEL1
#AW14 CLKGTY_GC_P
#AW13 CLKGTY_GC_N
#AY13 CLKGTY_GC_P
#BA13 CLKGTY_GC_N
#BA15 CLK50M
set_property PACKAGE_PIN BA40 [get_ports GTY_REFCLK_P[0]]
set_property PACKAGE_PIN BA41 [get_ports GTY_REFCLK_N[0]]
set_property PACKAGE_PIN AV38 [get_ports GTY_REFCLK_P[1]]
set_property PACKAGE_PIN AV39 [get_ports GTY_REFCLK_N[1]]
set_property PACKAGE_PIN AR36 [get_ports GTY_REFCLK_P[2]]
set_property PACKAGE_PIN AR37 [get_ports GTY_REFCLK_N[2]]
set_property PACKAGE_PIN AL36 [get_ports GTY_REFCLK_P[3]]
set_property PACKAGE_PIN AL37 [get_ports GTY_REFCLK_N[3]]
set_property PACKAGE_PIN AG36 [get_ports GTY_REFCLK_P[4]]
set_property PACKAGE_PIN AG37 [get_ports GTY_REFCLK_N[4]]
set_property PACKAGE_PIN AC36 [get_ports GTY_REFCLK_P[5]]
set_property PACKAGE_PIN AC37 [get_ports GTY_REFCLK_N[5]]
set_property PACKAGE_PIN W36 [get_ports GTY_REFCLK_P[6]]
set_property PACKAGE_PIN W37 [get_ports GTY_REFCLK_N[6]]
set_property PACKAGE_PIN R36 [get_ports GTY_REFCLK_P[7]]
set_property PACKAGE_PIN R36 [get_ports GTY_REFCLK_N[7]]


set_property PACKAGE_PIN {} [get_ports RXP_IN_GTY[*]]
set_property PACKAGE_PIN {} [get_ports RXN_IN_GTY[*]]
set_property PACKAGE_PIN {} [get_ports TXP_OUT_GTY[*]]
set_property PACKAGE_PIN {} [get_ports TXN_OUT_GTY[*]]


set_property PACKAGE_PIN BC45 [get_ports RXP_IN_GTY[0]]
set_property PACKAGE_PIN BC46 [get_ports RXN_IN_GTY[0]]
set_property PACKAGE_PIN AV43 [get_ports RXP_IN_GTY[1]]
set_property PACKAGE_PIN AV44 [get_ports RXN_IN_GTY[1]]
set_property PACKAGE_PIN BA45 [get_ports RXP_IN_GTY[2]]
set_property PACKAGE_PIN BA46 [get_ports RXN_IN_GTY[2]]
set_property PACKAGE_PIN AW45 [get_ports RXP_IN_GTY[3]]
set_property PACKAGE_PIN AW46 [get_ports RXN_IN_GTY[3]]
set_property PACKAGE_PIN AU45 [get_ports RXP_IN_GTY[4]]
set_property PACKAGE_PIN AU46 [get_ports RXN_IN_GTY[4]]
set_property PACKAGE_PIN AP43 [get_ports RXP_IN_GTY[5]]
set_property PACKAGE_PIN AP44 [get_ports RXN_IN_GTY[5]]
set_property PACKAGE_PIN AT43 [get_ports RXP_IN_GTY[6]]
set_property PACKAGE_PIN AT44 [get_ports RXN_IN_GTY[6]]
set_property PACKAGE_PIN AR45 [get_ports RXP_IN_GTY[7]]
set_property PACKAGE_PIN AR46 [get_ports RXN_IN_GTY[7]]
set_property PACKAGE_PIN AN45 [get_ports RXP_IN_GTY[8]]
set_property PACKAGE_PIN AN46 [get_ports RXN_IN_GTY[8]]
set_property PACKAGE_PIN AK43 [get_ports RXP_IN_GTY[9]]
set_property PACKAGE_PIN AK44 [get_ports RXN_IN_GTY[9]]
set_property PACKAGE_PIN AM43 [get_ports RXP_IN_GTY[10]]
set_property PACKAGE_PIN AM44 [get_ports RXN_IN_GTY[10]]
set_property PACKAGE_PIN AL45 [get_ports RXP_IN_GTY[11]]
set_property PACKAGE_PIN AL46 [get_ports RXN_IN_GTY[11]]
set_property PACKAGE_PIN AJ45 [get_ports RXP_IN_GTY[12]]
set_property PACKAGE_PIN AJ46 [get_ports RXN_IN_GTY[12]]
set_property PACKAGE_PIN AF43 [get_ports RXP_IN_GTY[13]]
set_property PACKAGE_PIN AF44 [get_ports RXN_IN_GTY[13]]
set_property PACKAGE_PIN AH43 [get_ports RXP_IN_GTY[14]]
set_property PACKAGE_PIN AH44 [get_ports RXN_IN_GTY[14]]
set_property PACKAGE_PIN AG45 [get_ports RXP_IN_GTY[15]]
set_property PACKAGE_PIN AG46 [get_ports RXN_IN_GTY[15]]
set_property PACKAGE_PIN AE45 [get_ports RXP_IN_GTY[16]]
set_property PACKAGE_PIN AE46 [get_ports RXN_IN_GTY[16]]
set_property PACKAGE_PIN AB43 [get_ports RXP_IN_GTY[17]]
set_property PACKAGE_PIN AB44 [get_ports RXN_IN_GTY[17]]
set_property PACKAGE_PIN AD43 [get_ports RXP_IN_GTY[18]]
set_property PACKAGE_PIN AD44 [get_ports RXN_IN_GTY[18]]
set_property PACKAGE_PIN AC45 [get_ports RXP_IN_GTY[19]]
set_property PACKAGE_PIN AC46 [get_ports RXN_IN_GTY[19]]
set_property PACKAGE_PIN AA45 [get_ports RXP_IN_GTY[20]]
set_property PACKAGE_PIN AA46 [get_ports RXN_IN_GTY[20]]
set_property PACKAGE_PIN V43 [get_ports RXP_IN_GTY[21]]
set_property PACKAGE_PIN V44 [get_ports RXN_IN_GTY[21]]
set_property PACKAGE_PIN Y43 [get_ports RXP_IN_GTY[22]]
set_property PACKAGE_PIN Y44 [get_ports RXN_IN_GTY[22]]
set_property PACKAGE_PIN W45 [get_ports RXP_IN_GTY[23]]
set_property PACKAGE_PIN W46 [get_ports RXN_IN_GTY[23]]
set_property PACKAGE_PIN U45 [get_ports RXP_IN_GTY[24]]
set_property PACKAGE_PIN U46 [get_ports RXN_IN_GTY[24]]
set_property PACKAGE_PIN P43 [get_ports RXP_IN_GTY[25]]
set_property PACKAGE_PIN P44 [get_ports RXN_IN_GTY[25]]
set_property PACKAGE_PIN T43 [get_ports RXP_IN_GTY[26]]
set_property PACKAGE_PIN T44 [get_ports RXN_IN_GTY[26]]
set_property PACKAGE_PIN R45 [get_ports RXP_IN_GTY[27]]
set_property PACKAGE_PIN R46 [get_ports RXN_IN_GTY[27]]
set_property PACKAGE_PIN N45 [get_ports RXP_IN_GTY[28]]
set_property PACKAGE_PIN N46 [get_ports RXN_IN_GTY[28]]
set_property PACKAGE_PIN K43 [get_ports RXP_IN_GTY[29]]
set_property PACKAGE_PIN K44 [get_ports RXN_IN_GTY[29]]
set_property PACKAGE_PIN M43 [get_ports RXP_IN_GTY[30]]
set_property PACKAGE_PIN M44 [get_ports RXN_IN_GTY[30]]
set_property PACKAGE_PIN L45 [get_ports RXP_IN_GTY[31]]
set_property PACKAGE_PIN L46 [get_ports RXN_IN_GTY[31]]



set_property PACKAGE_PIN BF42 [get_ports TXP_OUT_GTY[0]]
set_property PACKAGE_PIN BF43 [get_ports TXN_OUT_GTY[0]]
set_property PACKAGE_PIN AW40 [get_ports TXP_OUT_GTY[1]]
set_property PACKAGE_PIN AW41 [get_ports TXN_OUT_GTY[1]]
set_property PACKAGE_PIN BD42 [get_ports TXP_OUT_GTY[2]]
set_property PACKAGE_PIN BD43 [get_ports TXN_OUT_GTY[2]]
set_property PACKAGE_PIN BB42 [get_ports TXP_OUT_GTY[3]]
set_property PACKAGE_PIN BB43 [get_ports TXN_OUT_GTY[3]]
set_property PACKAGE_PIN AU40 [get_ports TXP_OUT_GTY[4]]
set_property PACKAGE_PIN AU41 [get_ports TXN_OUT_GTY[4]]
set_property PACKAGE_PIN AP38 [get_ports TXP_OUT_GTY[5]]
set_property PACKAGE_PIN AP39 [get_ports TXN_OUT_GTY[5]]
set_property PACKAGE_PIN AT38 [get_ports TXP_OUT_GTY[6]]
set_property PACKAGE_PIN AT39 [get_ports TXN_OUT_GTY[6]]
set_property PACKAGE_PIN AR40 [get_ports TXP_OUT_GTY[7]]
set_property PACKAGE_PIN AR41 [get_ports TXN_OUT_GTY[7]]
set_property PACKAGE_PIN AN40 [get_ports TXP_OUT_GTY[8]]
set_property PACKAGE_PIN AN41 [get_ports TXN_OUT_GTY[8]]
set_property PACKAGE_PIN AK38 [get_ports TXP_OUT_GTY[9]]
set_property PACKAGE_PIN AK39 [get_ports TXN_OUT_GTY[9]]
set_property PACKAGE_PIN AM38 [get_ports TXP_OUT_GTY[10]]
set_property PACKAGE_PIN AM39 [get_ports TXN_OUT_GTY[10]]
set_property PACKAGE_PIN AL40 [get_ports TXP_OUT_GTY[11]]
set_property PACKAGE_PIN AL41 [get_ports TXN_OUT_GTY[11]]
set_property PACKAGE_PIN AJ40 [get_ports TXP_OUT_GTY[12]]
set_property PACKAGE_PIN AJ41 [get_ports TXN_OUT_GTY[12]]
set_property PACKAGE_PIN AF38 [get_ports TXP_OUT_GTY[13]]
set_property PACKAGE_PIN AF39 [get_ports TXN_OUT_GTY[13]]
set_property PACKAGE_PIN AH38 [get_ports TXP_OUT_GTY[14]]
set_property PACKAGE_PIN AH39 [get_ports TXN_OUT_GTY[14]]
set_property PACKAGE_PIN AG40 [get_ports TXP_OUT_GTY[15]]
set_property PACKAGE_PIN AG41 [get_ports TXN_OUT_GTY[15]]
set_property PACKAGE_PIN AE40 [get_ports TXP_OUT_GTY[16]]
set_property PACKAGE_PIN AE41 [get_ports TXN_OUT_GTY[16]]
set_property PACKAGE_PIN AB38 [get_ports TXP_OUT_GTY[17]]
set_property PACKAGE_PIN AB39 [get_ports TXN_OUT_GTY[17]]
set_property PACKAGE_PIN AD38 [get_ports TXP_OUT_GTY[18]]
set_property PACKAGE_PIN AD39 [get_ports TXN_OUT_GTY[18]]
set_property PACKAGE_PIN AC40 [get_ports TXP_OUT_GTY[19]]
set_property PACKAGE_PIN AC41 [get_ports TXN_OUT_GTY[19]]
set_property PACKAGE_PIN AA40 [get_ports TXP_OUT_GTY[20]]
set_property PACKAGE_PIN AA41 [get_ports TXN_OUT_GTY[20]]
set_property PACKAGE_PIN V38 [get_ports TXP_OUT_GTY[21]]
set_property PACKAGE_PIN V39 [get_ports TXN_OUT_GTY[21]]
set_property PACKAGE_PIN Y38 [get_ports TXP_OUT_GTY[22]]
set_property PACKAGE_PIN Y39 [get_ports TXN_OUT_GTY[22]]
set_property PACKAGE_PIN W40 [get_ports TXP_OUT_GTY[23]]
set_property PACKAGE_PIN W41 [get_ports TXN_OUT_GTY[23]]
set_property PACKAGE_PIN U40 [get_ports TXP_OUT_GTY[24]]
set_property PACKAGE_PIN U41 [get_ports TXN_OUT_GTY[24]]
set_property PACKAGE_PIN P38 [get_ports TXP_OUT_GTY[25]]
set_property PACKAGE_PIN P39 [get_ports TXN_OUT_GTY[25]]
set_property PACKAGE_PIN T38 [get_ports TXP_OUT_GTY[26]]
set_property PACKAGE_PIN T39 [get_ports TXN_OUT_GTY[26]]
set_property PACKAGE_PIN R40 [get_ports TXP_OUT_GTY[27]]
set_property PACKAGE_PIN R41 [get_ports TXN_OUT_GTY[27]]
set_property PACKAGE_PIN N40 [get_ports TXP_OUT_GTY[28]]
set_property PACKAGE_PIN N41 [get_ports TXN_OUT_GTY[28]]
set_property PACKAGE_PIN J40 [get_ports TXP_OUT_GTY[29]]
set_property PACKAGE_PIN J41 [get_ports TXN_OUT_GTY[29]]
set_property PACKAGE_PIN M38 [get_ports TXP_OUT_GTY[30]]
set_property PACKAGE_PIN M39 [get_ports TXN_OUT_GTY[30]]
set_property PACKAGE_PIN L40 [get_ports TXP_OUT_GTY[31]]
set_property PACKAGE_PIN L41 [get_ports TXN_OUT_GTY[31]]


set_property PACKAGE_PIN AW9 [get_ports GTH_REFCLK_P[0]]
set_property PACKAGE_PIN AW8 [get_ports GTH_REFCLK_N[0]]
set_property PACKAGE_PIN AT11 [get_ports GTH_REFCLK_P[1]]
set_property PACKAGE_PIN AT10 [get_ports GTH_REFCLK_N[1]]
set_property PACKAGE_PIN AM11 [get_ports GTH_REFCLK_P[2]]
set_property PACKAGE_PIN AM10 [get_ports GTH_REFCLK_N[2]]
set_property PACKAGE_PIN AH11 [get_ports GTH_REFCLK_P[3]]
set_property PACKAGE_PIN AH10 [get_ports GTH_REFCLK_N[3]]
set_property PACKAGE_PIN AD11 [get_ports GTH_REFCLK_P[4]]
set_property PACKAGE_PIN AD10 [get_ports GTH_REFCLK_N[4]]
set_property PACKAGE_PIN Y11 [get_ports GTH_REFCLK_P[5]]
set_property PACKAGE_PIN Y10 [get_ports GTH_REFCLK_N[5]]
set_property PACKAGE_PIN T11 [get_ports GTH_REFCLK_P[6]]
set_property PACKAGE_PIN T10 [get_ports GTH_REFCLK_N[6]]
set_property PACKAGE_PIN M11 [get_ports GTH_REFCLK_P[7]]
set_property PACKAGE_PIN M10 [get_ports GTH_REFCLK_N[7]]


set_property PACKAGE_PIN {} [get_ports RXP_IN_GTH[*]]
set_property PACKAGE_PIN {} [get_ports RXN_IN_GTH[*]]
set_property PACKAGE_PIN {} [get_ports TXP_OUT_GTH[*]]
set_property PACKAGE_PIN {} [get_ports TXN_OUT_GTH[*]]

set_property PACKAGE_PIN AW4 [get_ports RXP_IN_GTH[0]]
set_property PACKAGE_PIN AW3 [get_ports RXN_IN_GTH[0]]
set_property PACKAGE_PIN BC2 [get_ports RXP_IN_GTH[1]]
set_property PACKAGE_PIN BC1 [get_ports RXN_IN_GTH[1]]
set_property PACKAGE_PIN AV2 [get_ports RXP_IN_GTH[2]]
set_property PACKAGE_PIN AV1 [get_ports RXN_IN_GTH[2]]
set_property PACKAGE_PIN BA2 [get_ports RXP_IN_GTH[3]]
set_property PACKAGE_PIN BA1 [get_ports RXN_IN_GTH[3]]
set_property PACKAGE_PIN AR4 [get_ports RXP_IN_GTH[4]]
set_property PACKAGE_PIN AR3 [get_ports RXN_IN_GTH[4]]
set_property PACKAGE_PIN AU4 [get_ports RXP_IN_GTH[5]]
set_property PACKAGE_PIN AU3 [get_ports RXN_IN_GTH[5]]
set_property PACKAGE_PIN AP2 [get_ports RXP_IN_GTH[6]]
set_property PACKAGE_PIN AP1 [get_ports RXN_IN_GTH[6]]
set_property PACKAGE_PIN AT2 [get_ports RXP_IN_GTH[7]]
set_property PACKAGE_PIN AT1 [get_ports RXN_IN_GTH[7]]
set_property PACKAGE_PIN AL4 [get_ports RXP_IN_GTH[8]]
set_property PACKAGE_PIN AL3 [get_ports RXN_IN_GTH[8]]
set_property PACKAGE_PIN AN4 [get_ports RXP_IN_GTH[9]]
set_property PACKAGE_PIN AN3 [get_ports RXN_IN_GTH[9]]
set_property PACKAGE_PIN AK2 [get_ports RXP_IN_GTH[10]]
set_property PACKAGE_PIN AK1 [get_ports RXN_IN_GTH[10]]
set_property PACKAGE_PIN AM2 [get_ports RXP_IN_GTH[11]]
set_property PACKAGE_PIN AM1 [get_ports RXN_IN_GTH[11]]
set_property PACKAGE_PIN AG4 [get_ports RXP_IN_GTH[12]]
set_property PACKAGE_PIN AG3 [get_ports RXN_IN_GTH[12]]
set_property PACKAGE_PIN AJ4 [get_ports RXP_IN_GTH[13]]
set_property PACKAGE_PIN AJ3 [get_ports RXN_IN_GTH[13]]
set_property PACKAGE_PIN AF2 [get_ports RXP_IN_GTH[14]]
set_property PACKAGE_PIN AF1 [get_ports RXN_IN_GTH[14]]
set_property PACKAGE_PIN AH2 [get_ports RXP_IN_GTH[15]]
set_property PACKAGE_PIN AH1 [get_ports RXN_IN_GTH[15]]
set_property PACKAGE_PIN W4 [get_ports RXP_IN_GTH[16]]
set_property PACKAGE_PIN W3 [get_ports RXN_IN_GTH[16]]
set_property PACKAGE_PIN AA4 [get_ports RXP_IN_GTH[17]]
set_property PACKAGE_PIN AA3 [get_ports RXN_IN_GTH[17]]
set_property PACKAGE_PIN V2 [get_ports RXP_IN_GTH[18]]
set_property PACKAGE_PIN V1 [get_ports RXN_IN_GTH[18]]
set_property PACKAGE_PIN Y2 [get_ports RXP_IN_GTH[19]]
set_property PACKAGE_PIN Y1 [get_ports RXN_IN_GTH[19]]
set_property PACKAGE_PIN R4 [get_ports RXP_IN_GTH[20]]
set_property PACKAGE_PIN R3 [get_ports RXN_IN_GTH[20]]
set_property PACKAGE_PIN U4 [get_ports RXP_IN_GTH[21]]
set_property PACKAGE_PIN U3 [get_ports RXN_IN_GTH[21]]
set_property PACKAGE_PIN P2 [get_ports RXP_IN_GTH[22]]
set_property PACKAGE_PIN P1 [get_ports RXN_IN_GTH[22]]
set_property PACKAGE_PIN T2 [get_ports RXP_IN_GTH[23]]
set_property PACKAGE_PIN T1 [get_ports RXN_IN_GTH[23]]
set_property PACKAGE_PIN L4 [get_ports RXP_IN_GTH[24]]
set_property PACKAGE_PIN L3 [get_ports RXN_IN_GTH[24]]
set_property PACKAGE_PIN N4 [get_ports RXP_IN_GTH[25]]
set_property PACKAGE_PIN N3 [get_ports RXN_IN_GTH[25]]
set_property PACKAGE_PIN K2 [get_ports RXP_IN_GTH[26]]
set_property PACKAGE_PIN K1 [get_ports RXN_IN_GTH[26]]
set_property PACKAGE_PIN M2 [get_ports RXP_IN_GTH[27]]
set_property PACKAGE_PIN M1 [get_ports RXN_IN_GTH[27]]
set_property PACKAGE_PIN R4 [get_ports RXP_IN_GTH[28]]
set_property PACKAGE_PIN R3 [get_ports RXN_IN_GTH[28]]
set_property PACKAGE_PIN U4 [get_ports RXP_IN_GTH[29]]
set_property PACKAGE_PIN U3 [get_ports RXN_IN_GTH[29]]
set_property PACKAGE_PIN P2 [get_ports RXP_IN_GTH[30]]
set_property PACKAGE_PIN P1 [get_ports RXN_IN_GTH[30]]
set_property PACKAGE_PIN T2 [get_ports RXP_IN_GTH[31]]
set_property PACKAGE_PIN T1 [get_ports RXN_IN_GTH[31]]

set_property PACKAGE_PIN BB5 [get_ports TXP_OUT_GTH[0]]
set_property PACKAGE_PIN BB4 [get_ports TXN_OUT_GTH[0]]
set_property PACKAGE_PIN BF5 [get_ports TXP_OUT_GTH[1]]
set_property PACKAGE_PIN BF4 [get_ports TXN_OUT_GTH[1]]
set_property PACKAGE_PIN AV7 [get_ports TXP_OUT_GTH[2]]
set_property PACKAGE_PIN AV6 [get_ports TXN_OUT_GTH[2]]
set_property PACKAGE_PIN BD5 [get_ports TXP_OUT_GTH[3]]
set_property PACKAGE_PIN BD4 [get_ports TXN_OUT_GTH[3]]
set_property PACKAGE_PIN AR9 [get_ports TXP_OUT_GTH[4]]
set_property PACKAGE_PIN AR8 [get_ports TXN_OUT_GTH[4]]
set_property PACKAGE_PIN AU9 [get_ports TXP_OUT_GTH[5]]
set_property PACKAGE_PIN AU8 [get_ports TXN_OUT_GTH[5]]
set_property PACKAGE_PIN AP7 [get_ports TXP_OUT_GTH[6]]
set_property PACKAGE_PIN AP6 [get_ports TXN_OUT_GTH[6]]
set_property PACKAGE_PIN AT7 [get_ports TXP_OUT_GTH[7]]
set_property PACKAGE_PIN AT6 [get_ports TXN_OUT_GTH[7]]
set_property PACKAGE_PIN AL9 [get_ports TXP_OUT_GTH[8]]
set_property PACKAGE_PIN AL8 [get_ports TXN_OUT_GTH[8]]
set_property PACKAGE_PIN AN9 [get_ports TXP_OUT_GTH[9]]
set_property PACKAGE_PIN AN8 [get_ports TXN_OUT_GTH[9]]
set_property PACKAGE_PIN AK7 [get_ports TXP_OUT_GTH[10]]
set_property PACKAGE_PIN AK6 [get_ports TXN_OUT_GTH[10]]
set_property PACKAGE_PIN AM7 [get_ports TXP_OUT_GTH[11]]
set_property PACKAGE_PIN AM6 [get_ports TXN_OUT_GTH[11]]
set_property PACKAGE_PIN AG9 [get_ports TXP_OUT_GTH[12]]
set_property PACKAGE_PIN AG8 [get_ports TXN_OUT_GTH[12]]
set_property PACKAGE_PIN AJ9 [get_ports TXP_OUT_GTH[13]]
set_property PACKAGE_PIN AJ8 [get_ports TXN_OUT_GTH[13]]
set_property PACKAGE_PIN AF7 [get_ports TXP_OUT_GTH[14]]
set_property PACKAGE_PIN AF6 [get_ports TXN_OUT_GTH[14]]
set_property PACKAGE_PIN AH7 [get_ports TXP_OUT_GTH[15]]
set_property PACKAGE_PIN AH6 [get_ports TXN_OUT_GTH[15]]
set_property PACKAGE_PIN AC9 [get_ports TXP_OUT_GTH[16]]
set_property PACKAGE_PIN AC8 [get_ports TXN_OUT_GTH[16]]
set_property PACKAGE_PIN AE9 [get_ports TXP_OUT_GTH[17]]
set_property PACKAGE_PIN AE8 [get_ports TXN_OUT_GTH[17]]
set_property PACKAGE_PIN AB7 [get_ports TXP_OUT_GTH[18]]
set_property PACKAGE_PIN AB6 [get_ports TXN_OUT_GTH[18]]
set_property PACKAGE_PIN AD7 [get_ports TXP_OUT_GTH[19]]
set_property PACKAGE_PIN AD6 [get_ports TXN_OUT_GTH[19]]
set_property PACKAGE_PIN W9 [get_ports TXP_OUT_GTH[20]]
set_property PACKAGE_PIN W8 [get_ports TXN_OUT_GTH[20]]
set_property PACKAGE_PIN AA9 [get_ports TXP_OUT_GTH[21]]
set_property PACKAGE_PIN AA8 [get_ports TXN_OUT_GTH[21]]
set_property PACKAGE_PIN V7 [get_ports TXP_OUT_GTH[22]]
set_property PACKAGE_PIN V6 [get_ports TXN_OUT_GTH[22]]
set_property PACKAGE_PIN Y7 [get_ports TXP_OUT_GTH[23]]
set_property PACKAGE_PIN Y6 [get_ports TXN_OUT_GTH[23]]
set_property PACKAGE_PIN R9 [get_ports TXP_OUT_GTH[24]]
set_property PACKAGE_PIN R8 [get_ports TXN_OUT_GTH[24]]
set_property PACKAGE_PIN U9 [get_ports TXP_OUT_GTH[25]]
set_property PACKAGE_PIN U8 [get_ports TXN_OUT_GTH[25]]
set_property PACKAGE_PIN P7 [get_ports TXP_OUT_GTH[26]]
set_property PACKAGE_PIN P6 [get_ports TXN_OUT_GTH[26]]
set_property PACKAGE_PIN T7 [get_ports TXP_OUT_GTH[27]]
set_property PACKAGE_PIN T6 [get_ports TXN_OUT_GTH[27]]
set_property PACKAGE_PIN L9 [get_ports TXP_OUT_GTH[28]]
set_property PACKAGE_PIN L8 [get_ports TXN_OUT_GTH[28]]
set_property PACKAGE_PIN N9 [get_ports TXP_OUT_GTH[29]]
set_property PACKAGE_PIN N8 [get_ports TXN_OUT_GTH[29]]
set_property PACKAGE_PIN K7 [get_ports TXP_OUT_GTH[30]]
set_property PACKAGE_PIN K6 [get_ports TXN_OUT_GTH[30]]
set_property PACKAGE_PIN M7 [get_ports TXP_OUT_GTH[31]]
set_property PACKAGE_PIN M6 [get_ports TXN_OUT_GTH[31]]




########

set_property IOSTANDARD LVCMOS18 [get_ports MGTY_RESETO_N]
set_property PACKAGE_PIN M22 [get_ports MGTY_RESETO_N]
set_property IOSTANDARD LVCMOS18 [get_ports MGTY_SCLO]
set_property PACKAGE_PIN P24 [get_ports MGTY_SCLO]
set_property IOSTANDARD LVCMOS18 [get_ports Y_MODPRS_N[0]]
set_property PACKAGE_PIN BF10 [get_ports Y_MODPRS_N[0]]
set_property IOSTANDARD LVCMOS18 [get_ports Y_MODPRS_N[1]]
set_property PACKAGE_PIN AR18 [get_ports Y_MODPRS_N[1]]
set_property IOSTANDARD LVCMOS18 [get_ports Y_MODPRS_N[2]]
set_property PACKAGE_PIN AT17 [get_ports Y_MODPRS_N[2]]
set_property IOSTANDARD LVCMOS18 [get_ports Y_MODPRS_N[3]]
set_property PACKAGE_PIN AT18 [get_ports Y_MODPRS_N[3]]
set_property IOSTANDARD LVCMOS18 [get_ports Y_MODPRS_N[4]]
set_property PACKAGE_PIN AU17 [get_ports Y_MODPRS_N[4]]
set_property IOSTANDARD LVCMOS18 [get_ports Y_MODPRS_N[5]]
set_property PACKAGE_PIN AV17 [get_ports Y_MODPRS_N[5]]
set_property IOSTANDARD LVCMOS18 [get_ports Y_MODPRS_N[6]]
set_property PACKAGE_PIN AT19 [get_ports Y_MODPRS_N[6]]
set_property IOSTANDARD LVCMOS18 [get_ports Y_MODPRS_N[7]]
set_property PACKAGE_PIN AU19 [get_ports Y_MODPRS_N[7]]
set_property IOSTANDARD LVCMOS18 [get_ports Y_LPMODE[0]]
set_property PACKAGE_PIN AV19 [get_ports Y_LPMODE[0]]
set_property IOSTANDARD LVCMOS18 [get_ports Y_LPMODE[1]]
set_property PACKAGE_PIN AW19 [get_ports Y_LPMODE[1]]
set_property IOSTANDARD LVCMOS18 [get_ports Y_LPMODE[2]]
set_property PACKAGE_PIN AY17 [get_ports Y_LPMODE[2]]
set_property IOSTANDARD LVCMOS18 [get_ports Y_LPMODE[3]]
set_property PACKAGE_PIN BA17 [get_ports Y_LPMODE[3]]
set_property IOSTANDARD LVCMOS18 [get_ports Y_LPMODE[4]]
set_property PACKAGE_PIN BB17 [get_ports Y_LPMODE[4]]
set_property IOSTANDARD LVCMOS18 [get_ports Y_LPMODE[5]]
set_property PACKAGE_PIN BC17 [get_ports Y_LPMODE[5]]
set_property IOSTANDARD LVCMOS18 [get_ports Y_LPMODE[6]]
set_property PACKAGE_PIN BE17 [get_ports Y_LPMODE[6]]
set_property IOSTANDARD LVCMOS18 [get_ports Y_LPMODE[7]]
set_property PACKAGE_PIN AY18 [get_ports Y_LPMODE[7]]
# ----------------------------------------------------------------------------------------------------------------------

#set_property IOSTANDARD LVCMOS18 [get_ports GTH_IO0_SCL]
#set_property PACKAGE_PIN AM20 [get_ports GTH_IO0_SCL]
#set_property IOSTANDARD LVCMOS18 [get_ports GTH_IO0_SDA]
#set_property PACKAGE_PIN AL20 [get_ports GTH_IO0_SDA]
#set_property IOSTANDARD LVCMOS18 [get_ports GTH_IO0_RESETX]
#set_property PACKAGE_PIN AL17 [get_ports GTH_IO0_RESETX]
#set_property IOSTANDARD LVCMOS18 [get_ports GTH_IO0_INTX]
#set_property PACKAGE_PIN AL19 [get_ports GTH_IO0_INTX]
#set_property IOSTANDARD LVCMOS18 [get_ports GTH_IO1_SCL]
#set_property PACKAGE_PIN AN16 [get_ports GTH_IO1_SCL]
#set_property IOSTANDARD LVCMOS18 [get_ports GTH_IO1_SDA]
#set_property PACKAGE_PIN AP16 [get_ports GTH_IO1_SDA]
#set_property IOSTANDARD LVCMOS18 [get_ports GTH_IO1_RESETX]
#set_property PACKAGE_PIN AM16 [get_ports GTH_IO1_RESETX]
#set_property IOSTANDARD LVCMOS18 [get_ports GTH_IO1_INTX]
#set_property PACKAGE_PIN AM19 [get_ports GTH_IO1_INTX]

set_property IOSTANDARD LVCMOS18 [get_ports RPT_CLK25M]
set_property PACKAGE_PIN P23 [get_ports RPT_CLK25M]
set_property IOSTANDARD LVCMOS18 [get_ports RPT_RSTX]
set_property PACKAGE_PIN N23 [get_ports RPT_RSTX]
set_property IOSTANDARD LVCMOS18 [get_ports GTH_RPT_SDA]
set_property PACKAGE_PIN AM17 [get_ports GTH_RPT_SDA]
set_property IOSTANDARD LVCMOS18 [get_ports GTH_RPT_SCL]
set_property PACKAGE_PIN AN19 [get_ports GTH_RPT_SCL]
set_property IOSTANDARD LVCMOS18 [get_ports MGTH_SDA]
set_property PACKAGE_PIN BE18 [get_ports MGTH_SDA]
set_property IOSTANDARD LVCMOS18 [get_ports MGTH_SCL]
set_property PACKAGE_PIN BD18 [get_ports MGTH_SCL]


# ----------------------------------------------------------------------------------------------------------------------

create_clock -period 6.400 -name CLK254M_M0GC [get_ports CLK254M_M0GC_P]
create_clock -period 6.400 -name CLK254M_M1GC [get_ports CLK254M_M1GC_P]
#create_clock -period 3.900 -name CLKGTY_GC [get_ports CLKGTY_GC_P]
#create_clock -period 3.900 -name CLKGTH_GC [get_ports CLKGTH_GC_P]
create_clock -period 6.400 -name CLKGTY_GC [get_ports CLKGTY_GC_P]
create_clock -period 6.400 -name CLKGTH_GC [get_ports CLKGTH_GC_P]
create_clock -period 6.400 -name GTYclk0 [get_ports GTY_REFCLK_P[*]]
#create_clock -period 3.900 -name GTHclk0 [get_ports GTH_REFCLK_P[*]]
create_clock -period 20.00 -name c50 [get_ports CLK50M]

set_input_jitter [get_clocks -of_objects [get_ports CLKGTY_GC_P]] 0.3
set_input_jitter [get_clocks -of_objects [get_ports CLKGTH_GC_P]] 0.3
set_input_jitter [get_clocks -of_objects [get_ports GTY_REFCLK_P[*]]] 0.3
set_input_jitter [get_clocks -of_objects [get_ports GTH_REFCLK_P[*]]] 0.3


#################################################################################################################################
# Transceiver Placement
# Full details of available transceiver locations can be found in the UltraScale documentation.
# These are sample constraints, please use correct locations for your chosen device using the same constraint format.
#################################################################################################################################
#set_property LOC GTHE3_CHANNEL_X0Y20 [get_cells -hierarchical -filter {NAME =~ *gen_channel_container[*].*gen_gthe3_channel_inst[*].GTHE3_CHANNEL_PRIM_INST}]

#-----------------------------------------------------------
# Clock source used for the IDELAY Controller (if present) -
#-----------------------------------------------------------


#create_clock -name io_refclk -period 3.333 [get_ports io_refclk]

#-----------------------------------------------------------
# Clock source used for the GT free running and DRP clock
#-----------------------------------------------------------

#create_clock -name independent_clock -period 20.00 [get_ports independent_clock]



#create_clock -add -name gtrefclk -period 6.40 [get_ports gtrefclk_p]

#create_clock -name gmii_tx_clk -period 8.000 [get_ports gmii_tx_clk]
#-----------------------------------------------------------
# GMII Tx Elastic Buffer Constraints                       -
#-----------------------------------------------------------

# Control Gray Code delay and skew across clock boundary
#set_false_path -to [get_pins -hier -filter {name =~ *tx_elastic_buffer_inst/reclock_rd_addrgray*/data_sync*/D}]
set_false_path -to [get_pins -of [get_cells -hierarchical -filter {NAME =~ *tx_elastic_buffer_inst/reclock_rd_addrgray*/data_sync*}] -filter {REF_PIN_NAME =~ D}]
#set_false_path -to [get_pins -hier -filter {name =~ *tx_elastic_buffer_inst/reclock_wr_addrgray*/data_sync*/D}]
set_false_path -to [get_pins -of [get_cells -hierarchical -filter {NAME =~ *tx_elastic_buffer_inst/reclock_wr_addrgray*/data_sync*}] -filter {REF_PIN_NAME =~ D}]

# Constrain between Distributed Memory (output data) and the 1st set of flip-flops
#set_false_path -from [get_clocks gmii_tx_clk] -to [get_pins -hier -filter {name =~ tx_elastic_buffer_inst/tx_en_fifo_reg1*/D}]
set_false_path -from [get_clocks gmii_clk] -to [get_pins -of [get_cells -hierarchical -filter {NAME =~ *tx_elastic_buffer_inst/tx_en_fifo_reg1*}] -filter {REF_PIN_NAME =~ D}]
#set_false_path -from [get_clocks gmii_tx_clk] -to [get_pins -hier -filter {name =~ tx_elastic_buffer_inst/tx_er_fifo_reg1*/D}]
set_false_path -from [get_clocks gmii_clk] -to [get_pins -of [get_cells -hierarchical -filter {NAME =~ *tx_elastic_buffer_inst/tx_er_fifo_reg1*}] -filter {REF_PIN_NAME =~ D}]
#set_false_path -from [get_clocks gmii_tx_clk] -to [get_pins -hier -filter {name =~ tx_elastic_buffer_inst/txd_fifo_reg1*/D}]
set_false_path -from [get_clocks gmii_clk] -to [get_pins -of [get_cells -hierarchical -filter {NAME =~ *tx_elastic_buffer_inst/txd_fifo_reg1*}] -filter {REF_PIN_NAME =~ D}]

#set_false_path -to [get_pins -hier -filter {name =~ *reset_sync*/PRE }]
set_false_path -to [get_pins -of [get_cells -hierarchical -filter {NAME =~ *reset_sync*}] -filter {REF_PIN_NAME =~ PRE}]

#set_false_path -to [get_pins */core_resets_i/pma_reset_pipe_reg*/PRE]
set_false_path -to [get_pins -of [get_cells -hierarchical -filter {NAME =~ *core_resets_i/pma_reset_pipe_reg*}] -filter {REF_PIN_NAME =~ PRE}]
#set_false_path -to [get_pins */core_resets_i/pma_reset_pipe*[0]/D]
set_false_path -to [get_pins -of [get_cells -hierarchical -filter {NAME =~ *core_resets_i/pma_reset_pipe*[0]}] -filter {REF_PIN_NAME =~ D}]
#set_false_path -to [get_pins -hier -filter {name =~ *core_idelayctrl_*/RST} -include_replicated_objects ]
#set_false_path -to [[get_pins -of [get_cells -hierarchical -filter {NAME =~ *core_idelayctrl_*}] -filter {REF_PIN_NAME =~ RST}] -include_replicated_objects ]

set_false_path -to [get_cells -hierarchical -filter {NAME =~ *sync*/i_in_meta_reg}]
set_false_path -to [get_pins -filter {REF_PIN_NAME=~*D} -of_objects [get_cells -hierarchical -filter {NAME =~ *sync*/rst_in_meta*}]]
set_false_path -to [get_pins -filter {REF_PIN_NAME=~*PRE} -of_objects [get_cells -hierarchical -filter {NAME =~ *sync*/rst_in_meta*}]]
set_false_path -to [get_pins -filter {REF_PIN_NAME=~*PRE} -of_objects [get_cells -hierarchical -filter {NAME =~ *sync*/rst_in_sync1*}]]
set_false_path -to [get_pins -filter {REF_PIN_NAME=~*PRE} -of_objects [get_cells -hierarchical -filter {NAME =~ *sync*/rst_in_sync2*}]]
set_false_path -to [get_pins -filter {REF_PIN_NAME=~*PRE} -of_objects [get_cells -hierarchical -filter {NAME =~ *sync*/rst_in_sync3*}]]
set_false_path -to [get_pins -filter {REF_PIN_NAME=~*PRE} -of_objects [get_cells -hierarchical -filter {NAME =~ *sync*/rst_in_out*}]]
